In [27]:
import numpy as np
import pandas as pd

In [28]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [29]:
df = pd.read_csv('houses.csv')
df.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
575,2 Bedroom House for sale in Sector 76 Gurgaon,https://www.99acres.com/2-bhk-bedroom-independ...,Suncity Avenue 76,75 Lac,"₹ 10,067/sq.ft.",(69 sq.m.) Plot Area,Plot area 745(69.21 sq.m.)Built Up area: 745 s...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 76 Gurgaon, Gurgaon, Haryana",11 Floors,North-East,Within 6 months,"['Omaxe Gurgaon Mall', 'Gurugram University', ...",500m from nh8\nClover leaf almost ready,NaN,"['Feng Shui / Vaastu Compliant', 'Maintenance ...",NaN,M67402042
865,4 Bedroom House for sale in Sector 56 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,2.99 Crore,"₹ 20,635/sq.ft.",(135 sq.m.) Plot Area,Plot area 161(134.62 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,"Pooja Room,Study Room,Servant Room","242, Sector 56 Gurgaon, Gurgaon, Haryana",2 Floors,South,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...",This 3 bhk house for sale in sector 56 gurgaon...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Safety4 out of 5', ...",N68716724
476,2 Bedroom House for sale in Palam Vihar Extension,https://www.99acres.com/2-bhk-bedroom-independ...,NaN,40 Lac,"₹ 7,619/sq.ft.",(49 sq.m.) Carpet Area,Carpet area: 525 (48.77 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Palam Vihar Extension, Palam Vihar Extension, ...",1 Floors,NaN,1 to 5 Year Old,NaN,Best in class property available at palam viha...,"['1 Fan', '1 Light', '1 Wardrobe', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",A68153088
979,5 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Eldeco Mansionz,5.15 Crore,"₹ 18,885/sq.ft.",(253 sq.m.) Plot Area,Plot area 303(253.35 sq.m.)Built Up area: 302 ...,5 Bedrooms,7 Bathrooms,3 Balconies,"Pooja Room,Servant Room","Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Eldeco mansioz 5bhk duplex villa semi furnishe...,"['7 Fan', '1 Exhaust Fan', '4 Geyser', '15 Lig...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Safety4 out of 5', ...",W62349350
795,5 Bedroom House for sale in Sector 33 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Unitech Uniworld Resorts,NaN,NaN,(420 sq.m.) Plot Area,Plot area 502(419.74 sq.m.),5 Bedrooms,7 Bathrooms,3+ Balconies,Servant Room,"A-8, Sector 33 Gurgaon, Gurgaon, Haryana",3 Floors,South-East,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",502 sqyd 5bhk villa available for sale at unit...,NaN,"['Private Garden / Terrace', 'High Ceiling Hei...","['Environment3 out of 5', 'Lifestyle4 out of 5...",H66359240

In [30]:
df.shape

(1044, 21)

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   str
 1   link             1044 non-null   str
 2   society          453 non-null    str
 3   price            968 non-null    str
 4   rate             1005 non-null   str
 5   area             1044 non-null   str
 6   areaWithType     987 non-null    str
 7   bedRoom          987 non-null    str
 8   bathroom         987 non-null    str
 9   balcony          987 non-null    str
 10  additionalRoom   589 non-null    str
 11  address          1031 non-null   str
 12  noOfFloor        967 non-null    str
 13  facing           674 non-null    str
 14  agePossession    987 non-null    str
 15  nearbyLocations  913 non-null    str
 16  description      1036 non-null   str
 17  furnishDetails   743 non-null    str
 18  features         674 non-null    str
 19  rating           907 non-null    str
 20  property_id      1036 non-null   str
dtypes: str(21)
memory usage: 171.4 KB

In [32]:
df.duplicated().sum()

np.int64(13)

In [33]:
df = df.drop_duplicates()

In [34]:
df.shape

(1031, 21)

In [35]:
df.isnull().sum()

property_name        0
link                 0
society            586
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     453
address             13
noOfFloor           76
facing             369
agePossession       57
nearbyLocations    131
description          8
furnishDetails     299
features           369
rating             137
property_id          8
dtype: int64

In [36]:
df.drop(columns=['link','property_id'], inplace=True)

In [37]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [38]:
df.rename(columns={'rate':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [39]:
df['society'].value_counts()

society
Emaar MGF Marbella                                   26
International City by SOBHA Phase 2                  26
Vipul Tatvam Villa                                   24
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             13
DLF City Plots Phase 2                               11
Unitech Espace                                       11
DLF City Plots                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Uppal Southend4.0 ★                                   7
Not Applicable                                        7
Sushant Lok 1 Builder Floors                          6
Ansals Palam Vihar                                    6
Experion Windchants3.8 ★                              5
DLF City Phase 1                                      5
Ansal Sushant Lok Plots4.1 ★                          4
nul                                                   4
DLF Alameda                                           4
Unitech Aspen Greens                                  4
Vatika India Next4.1 ★                                4
DLF City Plots Phase 3                                3
DLF New Town Heights 24.0 ★                           3
Puri Diplomatic Greens4.0 ★                           3
Tata Primanti4.1 ★                                    3
Anant Raj Estates                                     3
Central Park Flower Valley                            3
Housing Board Colony                                  3
Malibu Towne                                          3
Sector 14 RWA                                         3
Palam Vihar Extension West Zone RWA                   3
Rattan Garden                                         3
SS Aaron Ville                                        3
Vatika Signature Villas                               3
Eros Rosewood City4.0 ★                               3
Eros Rosewood Villas                                  3
Ansals Florence Villa                                 3
Unitech Nirvana Birch Court                           3
BPTP Astaire Gardens3.7 ★                             3
Luxury DLF City Floors                                2
Ansal API Esencia3.7 ★                                2
Suncity Essel Towers4.2 ★                             2
Emaar Emerald Hills4.1 ★                              2
Unitech Deerwood Chase                                2
shivpuri                                              2
Spaze Privy3.9 ★                                      2
Project Mianwali Colony                               2
Project Housing Board Colony                          2
Bestech Park View Ananda4.2 ★                         2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Sobha City                                            2
Ardee City3.8 ★                                       2
Unitech Escape3.8 ★                                   2
Satya The Hermitage3.5 ★                              2
Hans Enclave                                          2
Suncity Township4.1 ★                                 2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
SS Hibiscus                                           2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Silverglades Tarudhan Valley Golf Resort              2
Grover Homes Sec 4                                    1
FLOOR WISE DESIGNER KOTHI                             1
sector 37                                             1
DLF New Town Heights3.7 ★                             1
All Punjabi Welfare Association                       1
huda sector-56 gurgaon                                1
Sector-17C                                            1
private house                                         1
HUDA Ashok Vihar Phase 13.9 ★                         1
Ashok Vihar Phase 3 Gurgaon                           1
Farrukhnagar                                          1
Prem Kunj                                             1
secter 16a daultabad faridabad house no 313           1
rajendra park sec 105                                 1
Ansal Heights3.2 ★                                    1
Ninex City                                            1
Signature Global Park4.0 ★                            1
My Home                                               1
Surat nagar phase 2                                   1
DLF Gardencity Enclave                                1
Rajendra Park Gurgaon                                 1
house number B-34                                     1
ATS Tourmaline3.9 ★                                   1
Bhawani enclave                                       1
Om Nagar, Sector-11                                   1
DLF The Arbour                                        1
DLF Garden City Floors                                1
Huda Plots                                            1
Tulip Ivory3.5 ★                                      1
Emaar MGF The Palm Drive4.1 ★                         1
bhim nagar, sector 6                                  1
Anamika Enclave                                       1
MANOHAR NAGAR                                         1
Vatika Sovereign Next                                 1
Surendra Homes Dayanand Colony                        1
DLF The Grove                                         1
RK Excelo                                             1
Anand Garden, Sector-105                              1
Jacobpura Gurugram                                    1
Hero Homes                                            1
Ganpati Heights Apartment                             1
Smart World Gems                                      1
shree krishna homes                                   1
Tulip Yellow                                          1
HUDA Housing Board Colony4.1 ★                        1
Laxmi Garden Sector-11                                1
Ansal Celebrity Homes                                 1
Shri Shyam Residency                                  1
mian wali                                             1
HUDA Plot Sector 38                                   1
ROW HOUSE                                             1
Madan puri                                            1
Indiabulls Centrum Park3.7 ★                          1
Jacobpura                                             1
Huda Flats                                            1
Krishna Palace                                        1
Naman Residency                                       1
Sai Kripa Floors 5                                    1
DLF City Plot Phase 4                                 1
Signature Global City 92                              1
Bhim Nagar Society                                    1
Shivaji Nagar Residential                             1
Raj Villas                                            1
mahavir pura                                          1
jacob pura                                            1
Nirmal Enclave, Maruti Kunj Road                      1
Ansal Esencia Sovereign Floors                        1
Greenopolis                                           1
Vipul World3.9 ★                                      1
Sare Crescent Parc Royal Greens Phase 1               1
Anshul                                                1
SS Omnia                                              1
Suncity Avenue 76                                     1
Sheetla Enclave                                       1
sneh vihar                                            1
Adani Brahma Samsara4.2 ★                             1
DLF City Plot Phase 3                                 1
Signature Global City 63A                             1
rattan vihar rajendra park                            1
Ashok vihar phase III Extension                       1
Ansal                                                 1
Nitin Vihar                                           1
Sector 15 Part 2 RWA                                  1
u block dlf phase 3 road no 21                        1
cloudnine cottages                                    1
Landmark House                                        1
nirvana country                                       1
DLF City Plots Phase 4                                1
Kothi                                                 1
Birla Navya                                           1
Central Park Flower Valley Cerise Floors              1
Ansal API Spanish Court                               1
4S Aradhya Homes                                      1
Ireo Victory Valley4.1 ★                              1
Ansal Florence Super                                  1
Smart World Orchard                                   1
Unitech South City 23.8 ★                             1
DLF Floors Phase 3                                    1
Ansal Sushant Residency                               1
DLF South City 1                                      1
Signature Global City                                 1
Signature Global City 81                              1
Central Park                                          1
Ansal Sushant Lok                                     1
Nirvana Country                                       1
Vatika The Seven Lamps3.8 ★                           1
Unitech Greenwood City3.6 ★                           1
Independent House Sector 45                           1
Ireo Victory Valley4.0 ★                              1
Satya The Legend3.8 ★                                 1
DLF Pink Town House4.0 ★                              1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Vatika Independent Floors3.8 ★                        1
The Laburnum                                          1
Ansal Sushant Lok 2                                   1
Godrej Meridien                                       1
Sector 57 Huda                                        1
Huda                                                  1
Huda Floor                                            1
Name: count, dtype: int64

In [40]:
df['society'].value_counts().shape

(185,)

In [41]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [42]:
df['society'].isnull().sum()

np.int64(0)

In [43]:
df['society'] = df['society'].str.replace('nan','independent')

In [44]:
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
5 Crore             13
4.5 Crore           13
70 Lac              13
75 Lac              13
50 Lac              13
8 Crore             13
8.5 Crore           12
7 Crore             12
85 Lac              12
4 Crore             11
1.5 Crore           11
9 Crore             10
10 Crore            10
2.5 Crore           10
2.25 Crore          10
90 Lac              10
45 Lac              10
60 Lac              10
Price on Request    10
12 Crore             9
2 Crore              9
9.5 Crore            9
1.1 Crore            9
80 Lac               9
1.7 Crore            9
1 Crore              8
1.6 Crore            8
4.6 Crore            8
11 Crore             8
6.75 Crore           8
2.1 Crore            7
3.75 Crore           7
12.5 Crore           7
65 Lac               7
55 Lac               7
95 Lac               7
1.3 Crore            7
1.2 Crore            7
1.35 Crore           7
40 Lac               7
5.7 Crore            6
13.5 Crore           6
6.25 Crore           6
3.25 Crore           6
7.5 Crore            6
3.6 Crore            6
1.45 Crore           6
2.75 Crore           6
1.15 Crore           6
2.95 Crore           6
16 Crore             6
4.25 Crore           6
10.5 Crore           6
3 Crore              5
15 Crore             5
4.75 Crore           5
5.6 Crore            5
7.25 Crore           5
35 Lac               5
2.8 Crore            5
1.25 Crore           5
1.8 Crore            5
38 Lac               5
5.25 Crore           4
8.25 Crore           4
3.3 Crore            4
13 Crore             4
5.8 Crore            4
5.75 Crore           4
17 Crore             4
3.2 Crore            4
11.5 Crore           4
6.8 Crore            4
42 Lac               4
2.4 Crore            4
37 Lac               4
4.7 Crore            4
1.65 Crore           4
1.4 Crore            4
4.35 Crore           4
18 Crore             4
9.25 Crore           4
20 Crore             3
1.95 Crore           3
4.45 Crore           3
7.35 Crore           3
3.4 Crore            3
8.4 Crore            3
7.2 Crore            3
5.65 Crore           3
1.55 Crore           3
3.85 Crore           3
3.1 Crore            3
6.95 Crore           3
2.2 Crore            3
82 Lac               3
1.16 Crore           3
34 Lac               3
49 Lac               3
62 Lac               3
2.3 Crore            3
32 Lac               3
5.15 Crore           3
92 Lac               3
1.85 Crore           3
4.3 Crore            3
1.9 Crore            3
2.9 Crore            3
19 Crore             3
6.4 Crore            3
10.85 Crore          2
11.95 Crore          2
2.55 Crore           2
3.55 Crore           2
10.45 Crore          2
19.5 Crore           2
67 Lac               2
3.05 Crore           2
6.3 Crore            2
58 Lac               2
11.25 Crore          2
66 Lac               2
48 Lac               2
36 Lac               2
1.75 Crore           2
30 Lac               2
14 Crore             2
1.05 Crore           2
3.35 Crore           2
3.15 Crore           2
89 Lac               2
9.9 Crore            2
2.15 Crore           2
58.25 Lac            2
15.5 Crore           2
10.55 Crore          2
3.65 Crore           2
26 Crore             2
3.51 Crore           2
8.49 Crore           2
4.95 Crore           2
7.1 Crore            2
11.75 Crore          2
10.75 Crore          1
7.6 Crore            1
10.56 Crore          1
5.46 Crore           1
55.11 Lac            1
7.49 Crore           1
12.39 Crore          1
5.4 Crore            1
7.99 Crore           1
8.8 Crore            1
7.69 Crore           1
8.7 Crore            1
6.2 Crore            1
5.9 Crore            1
5.85 Crore           1
5.35 Crore           1
6.6 Crore            1
61 Lac               1
7.05 Crore           1
3.69 Crore           1
11.3 Crore           1
4.02 Crore           1
3.93 Crore           1
15.5 Lac             1
4.12 Crore           1
1.87 Crore           1
22 Lac               1
3.12 Crore           1
7.5 Lac              1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
1.72 Crore           1
78 Lac               1
1.52 Crore           1
52 Lac               1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
5.2 Crore            1
42.75 Lac            1
47 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
29 Lac               1
24 Lac               1
44 Lac               1
83 Lac               1
98 Lac               1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
13 Lac               1
96 Lac               1
18.02 Crore          1
65.8 Lac             1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
59 Lac               1
27 Lac               1
8.1 Crore            1
14.75 Crore          1
9.54 Crore           1
17.3 Crore           1
18.9 Crore           1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.99 Crore           1
6.81 Crore           1
8.81 Crore           1
8.9 Crore            1
4.49 Crore           1
22 Crore             1
4.15 Crore           1
7.3 Crore            1
18.5 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
5.1 Crore            1
3.9 Crore            1
2.01 Crore           1
5.88 Crore           1
52.75 Lac            1
46.75 Lac            1
12.25 Crore          1
9.4 Crore            1
10.3 Crore           1
8.45 Crore           1
6.15 Crore           1
2.47 Crore           1
3.7 Crore            1
18.4 Crore           1
4.4 Crore            1
99 Lac               1
2.65 Crore           1
1.27 Crore           1
11.29 Crore          1
4.31 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
5.51 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
1.04 Crore           1
9.85 Crore           1
1.18 Crore           1
15.1 Crore           1
9.01 Crore           1
9.8 Crore            1
4.99 Crore           1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [24]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
260,2 Bedroom House for sale in Sector 8 Gurgaon,independent,Price on Request,NaN,(74 sq.m.) Built-up Area,Built Up area: 800 (74.32 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 8 Gurgaon, Gurgaon, Haryana",1 Floors,NaN,undefined,NaN,"1 bath, semi-Furnished, at sector 8 location g...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
261,3 Bedroom House for sale in Dharam Colony,independent,Price on Request,NaN,(93 sq.m.) Carpet Area,Carpet area: 1000 (92.9 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Dharam Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, at dharam colony location...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
290,5 Bedroom House for sale in Laxman Vihar,independent,Price on Request,NaN,(167 sq.m.) Built-up Area,Built Up area: 1800 (167.23 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,NaN,"Phase 2, Laxman Vihar, Gurgaon, Haryana",2 Floors,North,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","8 bath, unfurnished, overlooking main road, no...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
291,3 Bedroom House for sale in Laxman Vihar,independent,Price on Request,NaN,(223 sq.m.) Built-up Area,Built Up area: 2400 (222.97 sq.m.)Carpet area:...,3 Bedrooms,4 Bathrooms,2 Balconies,NaN,"1248 B, Near Hanuman Mandir, Laxman Vihar, Gur...",2 Floors,NaN,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","4 bath, unfurnished, 1st floor (Of 2), 1 side ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
355,7 Bedroom House for sale in Rajendra Park,independent,Price on Request,NaN,(585 sq.m.) Built-up Area,Built Up area: 700 (585.29 sq.m.),7 Bedrooms,6 Bathrooms,3 Balconies,NaN,"Rajendra Park, Gurgaon, Haryana",4 Floors,NaN,5 to 10 Year Old,NaN,"6 bath, furnished, 2 side open, at rajendra pa...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
384,3 Bedroom House for sale in Ansal Plaza,independent,Price on Request,NaN,(40 sq.m.) Carpet Area,Carpet area: 429 (39.86 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Ansal Plaza, Sector 23, Ansal Plaza, Gurgaon, ...",4 Floors,NaN,undefined,NaN,Best in class property available at ansal plaz...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
447,2 Bedroom House for sale in Sheetla Colony,independent,Price on Request,NaN,(42 sq.m.) Plot Area,Plot area 50(41.81 sq.m.)Built Up area: 720 sq...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sheetla Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, semi-Furnished, at sheetla colony loca...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5..."
522,5 Bedroom House for sale in Surat Nagar,independent,Price on Request,NaN,(54 sq.m.) Built-up Area,Built Up area: 65 (54.35 sq.m.),5 Bedrooms,2 Bathrooms,No Balcony,NaN,"Surat Nagar Phase 2, Sector 104, Surat Nagar, ...",2 Floors,NaN,undefined,NaN,5bhk residential house for resale in surat nag...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5..."
548,2 Bedroom House for sale in Dharam Colony Block E,independent,Price on Request,NaN,(84 sq.m.) Built-up Area,Built Up area: 900 (83.61 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Dharam Colony Block E, Gurgaon, Haryana",1 Floors,NaN,undefined,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","1 bath, unfurnished, ground floor (Of 1), at d...",NaN,NaN,NaN
621,4 Bedroom House for sale in Madanpuri,independent,Price on Request,NaN,(167 sq.m.) Carpet Area,Carpet area: 1800 (167.23 sq.m.),4 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Madanpuri, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 1 side open, at madan pur...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [45]:
def convert_to_crore(price):

    if pd.isna(price):
        return np.nan

    price = str(price)

    if "Crore" in price:
        return round(float(price.split()[0]),2)

    elif "Lac" in price:
        return round(float(price.split()[0]) / 100,2)

    else:
        return np.nan

In [46]:
df['price'] = df['price'].apply(convert_to_crore)

In [48]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

df['price'] = imputer.fit_transform(df[['price']])

In [50]:
df['price'].value_counts()

price
3.60     92
3.50     19
5.50     17
6.50     16
6.00     14
5.00     13
4.50     13
0.70     13
0.75     13
0.50     13
8.00     13
8.50     12
7.00     12
0.85     12
4.00     11
0.60     11
1.50     11
9.00     10
10.00    10
2.50     10
2.25     10
0.90     10
0.45     10
12.00     9
2.00      9
9.50      9
1.10      9
0.80      9
1.70      9
0.55      8
1.00      8
1.60      8
4.60      8
11.00     8
6.75      8
2.10      7
3.75      7
12.50     7
0.65      7
0.95      7
1.30      7
1.20      7
1.35      7
0.40      7
5.70      6
13.50     6
6.25      6
3.25      6
7.50      6
1.45      6
2.75      6
1.15      6
2.95      6
16.00     6
4.25      6
10.50     6
3.00      5
15.00     5
4.75      5
5.60      5
7.25      5
0.35      5
2.80      5
1.25      5
1.80      5
0.38      5
5.25      4
8.25      4
3.30      4
13.00     4
5.80      4
5.75      4
17.00     4
3.20      4
11.50     4
6.80      4
0.58      4
0.42      4
2.40      4
0.37      4
4.70      4
1.65      4
1.40      4
4.35      4
18.00     4
9.25      4
20.00     3
1.95      3
4.45      3
7.35      3
3.40      3
8.40      3
7.20      3
5.65      3
1.55      3
3.85      3
3.10      3
6.95      3
0.66      3
2.20      3
0.82      3
1.16      3
0.34      3
0.49      3
0.62      3
2.30      3
0.53      3
0.32      3
5.15      3
0.92      3
1.85      3
4.30      3
0.47      3
1.90      3
2.90      3
19.00     3
6.40      3
10.85     2
11.95     2
2.55      2
3.55      2
10.45     2
19.50     2
0.67      2
3.05      2
6.30      2
11.25     2
0.48      2
0.36      2
1.75      2
0.30      2
14.00     2
1.05      2
3.35      2
3.15      2
0.89      2
9.90      2
2.15      2
15.50     2
10.55     2
3.65      2
26.00     2
3.51      2
8.49      2
4.95      2
7.10      2
11.75     2
10.75     1
7.60      1
10.56     1
5.46      1
7.49      1
12.39     1
5.40      1
7.99      1
8.80      1
7.69      1
8.70      1
6.20      1
5.90      1
5.85      1
5.35      1
6.60      1
0.61      1
7.05      1
3.69      1
11.30     1
4.02      1
3.93      1
0.15      1
4.12      1
1.87      1
0.22      1
3.12      1
0.07      1
2.58      1
8.95      1
13.20     1
0.51      1
0.63      1
1.72      1
0.78      1
1.52      1
0.52      1
4.65      1
6.10      1
0.68      1
1.07      1
5.20      1
0.43      1
0.71      1
1.44      1
3.71      1
0.18      1
3.08      1
0.29      1
0.24      1
0.44      1
0.83      1
0.98      1
3.09      1
0.74      1
0.69      1
2.43      1
0.13      1
0.96      1
18.02     1
1.34      1
0.46      1
2.60      1
3.87      1
1.39      1
0.59      1
0.27      1
8.10      1
14.75     1
9.54      1
17.30     1
18.90     1
24.00     1
7.46      1
3.99      1
6.81      1
8.81      1
8.90      1
4.49      1
22.00     1
4.15      1
7.30      1
18.50     1
27.50     1
8.31      1
6.21      1
1.83      1
5.10      1
3.90      1
2.01      1
5.88      1
12.25     1
9.40      1
10.30     1
8.45      1
6.15      1
2.47      1
3.70      1
18.40     1
4.40      1
0.99      1
2.65      1
1.27      1
11.29     1
4.31      1
11.58     1
8.48      1
8.20      1
5.51      1
3.49      1
2.99      1
9.19      1
1.64      1
9.35      1
4.05      1
8.75      1
23.00     1
2.45      1
7.85      1
25.00     1
2.68      1
2.70      1
1.04      1
9.85      1
1.18      1
15.10     1
9.01      1
9.80      1
4.99      1
8.60      1
9.55      1
2.35      1
18.25     1
5.30      1
10.80     1
31.50     1
4.10      1
7.65      1
6.46      1
6.44      1
7.80      1
3.80      1
7.45      1
7.42      1
6.09      1
2.98      1
Name: count, dtype: int64

In [51]:
df['price'].isnull().sum()

np.int64(0)

In [52]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 22,222/sq.ft.     14
₹ 33,333/sq.ft.     11
₹ 11,111/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 37,037/sq.ft.      6
₹ 30,556/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 13,333/sq.ft.      6
₹ 26,667/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 23,333/sq.ft.      5
₹ 11,100/sq.ft.      5
₹ 23,148/sq.ft.      5
₹ 8,000/sq.ft.       5
₹ 8,889/sq.ft.       5
₹ 9,444/sq.ft.       5
₹ 5,000/sq.ft.       5
₹ 27,778/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 25,000/sq.ft.      4
₹ 6,944/sq.ft.       4
₹ 18,889/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 35,000/sq.ft.      4
₹ 32,407/sq.ft.      4
₹ 25,926/sq.ft.      3
₹ 32,222/sq.ft.      3
₹ 50,000/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 16,058/sq.ft.      3
₹ 10,556/sq.ft.      3
₹ 13,889/sq.ft.      3
₹ 15,625/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 12,000/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 60,000/sq.ft.      3
₹ 12,222/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 7,500/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 8,444/sq.ft.       3
₹ 15,555/sq.ft.      3
₹ 14,815/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 32,963/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 24,500/sq.ft.      2
₹ 7,058/sq.ft.       2
₹ 13,622/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 19,708/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 24,845/sq.ft.      2
₹ 9,000/sq.ft.       2
₹ 100,000/sq.ft.     2
₹ 26,852/sq.ft.      2
₹ 7,407/sq.ft.       2
₹ 8,888/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 21,759/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 15,257/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 10,753/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 20,635/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 12,500/sq.ft.      2
₹ 17,037/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 17,778/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 35,185/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 45,833/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 44,444/sq.ft.      2
₹ 23,457/sq.ft.      2
₹ 9,634/sq.ft.       2
₹ 24,155/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 20,115/sq.ft.      1
₹ 105,751/sq.ft.     1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 28,490/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 13,542/sq.ft.      1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 21,000/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 38,667/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 4,074/sq.ft.       1
₹ 630/sq.ft.         1
₹ 86,567/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 14,729/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 7,309/sq.ft.       1
₹ 74,074/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 138,888/sq.ft.     1
₹ 7,666/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 8,486/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 8,411/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 21,667/sq.ft.      1
₹ 20,425/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 17,695/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 40,909/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 4,808/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 6,567/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 66,666/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 21,111/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 19,869/sq.ft.      1
₹ 8,796/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 5,658/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 5,778/sq.ft.       1
₹ 6,111/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 120,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 73,333/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 315,789/sq.ft.     1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 151/sq.ft.         1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 35,494/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 7,576/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 232/sq.ft.         1
₹ 218,750/sq.ft.     1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 37,313/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 10,122/sq.ft.      1
₹ 8,642/sq.ft.       1
₹ 6,481/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 11,904/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 183,333/sq.ft.     1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 19,818/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 7,619/sq.ft.       1
₹ 98,214/sq.ft.      1
₹ 13,499/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 20,062/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 17,500/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 181,818/sq.ft.     1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 5,333/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,397/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 6,981/sq.ft.       1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 6,800/sq.ft.       1
₹ 7,333/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 7,539/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 28,898/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 20,444/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 17,857/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 14,166/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 7,777/sq.ft.       1
₹ 18,658/sq.ft.      1
₹ 10,484/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 8,127/sq.ft.       1
₹ 7,555/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 10,610/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 8,155/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 24,074/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 9,615/sq.ft.       1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 25,463/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 5,128/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 15,926/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 23,889/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 36,911/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 27,191/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 33,592/sq.ft.      1
₹ 24,455/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 18,444/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 42,054/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 20,741/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 18,888/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 20,988/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 21,296/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 22,812/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 178,571/sq.ft.     1
₹ 27,461/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 21,242/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 19,360/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 40,850/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 30,864/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 16,056/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 7,718/sq.ft.       1
₹ 25,535/sq.ft.      1
₹ 1,859/sq.ft.       1
₹ 10,579/sq.ft.      1
₹ 42,194/sq.ft.      1
₹ 15,278/sq.ft.      1
₹ 201,388/sq.ft.     1
₹ 17,187/sq.ft.      1
₹ 18,928/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 7,827/sq.ft.       1
₹ 23,556/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 28,233/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 19,645/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 14,667/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 9,349/sq.ft.       1
₹ 23,504/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 21,786/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 12,393/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 26,502/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 47,803/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 33,665/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 28,787/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 33,129/sq.ft.      1
Name: count, dtype: int64

In [53]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [54]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     233
5 Bedrooms     196
3 Bedrooms     149
2 Bedrooms      91
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      32
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
21 Bedrooms      1
20 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [55]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
62,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,3.6,13622.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
63,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,3.6,13909.0,(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
66,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
67,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,16058.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
68,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,3.6,13623.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
69,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,3.6,13910.0,(294-418 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
70,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,3.6,13910.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
71,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,3.6,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
72,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
73,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
74,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
75,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,3.6,13331.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
76,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,3.6,11100.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
77,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,3.6,11100.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
78,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,3.6,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
81,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
82,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
83,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,3.6,11100.0,(325 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
84,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,3.6,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
85,4 Bedroom House for sale in Sector 23 Gurgaon,all punjabi welfare association,3.6,16999.0,(139-279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 23 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['HUDA Sector 23 Market', 'Palam triangle', 'R...",All punjabi welfare association in sector-23 g...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
86,4 Bedroom House for sale in Sector 72 Gurgaon,tata primanti,3.6,10714.0,(650-790 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 72 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Tata primanti in sector-72, gurgaon by tata ho...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4.5 out ..."
87,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,3.6,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
88,5 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,3.6,NaN,(251-704 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
89,3 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,3.6,NaN,(211 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
92,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,3.6,18750.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
93,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,3.6,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
94,5 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,3.6,27793.0,(571-711 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
95,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,3.6,22006.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
96,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,3.6,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
97,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,3.6,13333.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
98,5 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,3.6,22222.0,(293-381 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
99,4 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,3.6,28760.0,(207 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
100,3 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,3.6,16975.0,(301 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
102,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
103,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,3.6,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
104,4 Bedroom House for sale in Sector 65 Gurgaon,emaar emerald hills,3.6,NaN,(183 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 65 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Emerald Plaza Shopping Mall', 'Southern Peri...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
105,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,3.6,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
110,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,3.6,12828.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
111,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,3.6,12842.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
115,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,3.6,NaN,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
273,5 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,3.6,NaN,(509-543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Metro Station Kankrola sec 87', 'Sapphire 83...","Bestech park view ananda in sector-81 gurgaon,...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
277,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,3.6,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
278,6 Bedroom House for sale in Sector 70 Gurgaon,tulip ivory,3.6,NaN,(697 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 70 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Reach 3 Roads Shopping Mall', 'Southern Peri...","Tulip ivory in sector-70, gurgaon by tulip inf...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
284,3 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf the palm drive,3.6,NaN,(353 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf the palm drive in sector-66, gurgaon...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
292,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,3.6,13622.0,(540 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
293,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,3.6,14045.0,(363 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
294,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,3.6,10783.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
295,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,3.6,10804.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
296,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,3.6,10783.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
318,3 Bedroom House for sale in Arjun Nagar,independent,3.6,13333.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,2 Bedroom House for sale in Palam Vihar Extension,independent,3.6,6666.0,(49 sq.m.) Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,2 Bedroom House for sale in Rajiv Nagar,independent,3.6,66666.0,(7 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,7 Bedroom House for sale in Surya Vihar,independent,3.6,7500.0,(372 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,2 Bedroom House for sale in Sector 5 Gurgaon,independent,3.6,25000.0,(93 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,4 Bedroom House for sale in Sohna,independent,3.6,6944.0,(167 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,4 Bedroom House for sale in Sector 52 Gurgaon,independent,3.6,NaN,(201 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,6 Bedroom House for sale in Sector 22 Gurgaon,saksham welfare association,3.6,19645.0,(220 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df = df[~df['bedRoom'].isnull()]

In [57]:
df.shape

(974, 19)

In [58]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [59]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     229
3 Bathrooms     166
5 Bathrooms     137
2 Bathrooms     118
6 Bathrooms      83
1 Bathroom       67
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      29
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
13 Bathrooms      4
18 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [60]:
df['bathroom'].isnull().sum()

np.int64(0)

In [61]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [62]:
df['balcony'].value_counts()

balcony
3+ Balconies    366
2 Balconies     221
3 Balconies     161
No Balcony      118
1 Balcony       108
Name: count, dtype: int64

In [63]:
df['balcony'].isnull().sum()

np.int64(0)

In [64]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [65]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Others                                11
Pooja Room,Store Room                            11
Pooja Room,Store Room,Study Room,Servant Room     8
Servant Room,Others                               8
Servant Room,Pooja Room                           8
Pooja Room,Servant Room,Store Room                7
Servant Room,Pooja Room,Store Room                6
Study Room,Servant Room,Pooja Room,Store Room     6
Store Room,Servant Room                           6
Study Room,Pooja Room,Servant Room                5
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Servant Room,Store Room,Pooja Room     4
Servant Room,Store Room,Pooja Room                4
Pooja Room,Study Room,Others                      4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room                4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Store Room,Pooja Room,Servant Room                2
Store Room,Pooja Room,Study Room                  2
Study Room,Pooja Room,Store Room                  2
Servant Room,Study Room,Pooja Room                2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Servant Room,Others                    2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Pooja Room                             2
Study Room,Pooja Room,Store Room,Servant Room     2
Servant Room,Study Room,Store Room,Pooja Room     1
Study Room,Store Room,Pooja Room                  1
Study Room,Store Room                             1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [66]:
df['additionalRoom'].fillna('not available',inplace=True)

C:\Users\ARCHIT\AppData\Local\Temp\ipykernel_30692\1615843200.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['additionalRoom'].fillna('not available',inplace=True)

0                                        Servant Room
1                  Store Room,Pooja Room,Servant Room
2                                        Servant Room
3                                        Servant Room
4                                              Others
5                                        Servant Room
6                  Servant Room,Pooja Room,Store Room
7                                        Servant Room
8                                          Store Room
9                                        Servant Room
10                                         Store Room
11      Study Room,Servant Room,Pooja Room,Store Room
12                                         Pooja Room
13      Pooja Room,Study Room,Servant Room,Store Room
14      Study Room,Servant Room,Store Room,Pooja Room
15                              Pooja Room,Study Room
16                 Servant Room,Pooja Room,Store Room
17                   Store Room,Pooja Room,Study Room
18                            Pooja Room,Servant Room
19      Pooja Room,Study Room,Servant Room,Store Room
20                                      not available
21                            Store Room,Servant Room
22                            Pooja Room,Servant Room
23                 Pooja Room,Servant Room,Store Room
24                   Study Room,Pooja Room,Store Room
25                 Pooja Room,Study Room,Servant Room
26                 Pooja Room,Study Room,Servant Room
27                                         Study Room
28                            Servant Room,Store Room
29                                       Servant Room
30                   Pooja Room,Study Room,Store Room
31                            Store Room,Servant Room
32                                         Pooja Room
33                                       Servant Room
34                                      not available
35                                         Store Room
36      Pooja Room,Study Room,Servant Room,Store Room
37                                         Store Room
38                                         Study Room
39      Pooja Room,Study Room,Servant Room,Store Room
40      Pooja Room,Study Room,Servant Room,Store Room
41                                         Store Room
42                 Study Room,Pooja Room,Servant Room
43          Pooja Room,Study Room,Servant Room,Others
44                                       Servant Room
45                            Pooja Room,Servant Room
46                            Pooja Room,Servant Room
47                 Pooja Room,Study Room,Servant Room
48      Pooja Room,Store Room,Study Room,Servant Room
49                 Servant Room,Pooja Room,Store Room
50                                      not available
51      Pooja Room,Study Room,Servant Room,Store Room
52      Pooja Room,Study Room,Servant Room,Store Room
53                 Servant Room,Store Room,Pooja Room
54                                             Others
55      Servant Room,Study Room,Store Room,Pooja Room
56                 Pooja Room,Study Room,Servant Room
57                                      not available
58      Pooja Room,Study Room,Servant Room,Store Room
59      Study Room,Servant Room,Pooja Room,Store Room
60                                       Servant Room
61                                             Others
64                                      not available
65                            Pooja Room,Servant Room
79                                         Store Room
80                                      not available
90                                       Servant Room
91                                Servant Room,Others
101                Servant Room,Pooja Room,Store Room
106                                     not available
107                                     not available
108                Servant Room,Study Room,Pooja Room
109     Pooja Room,Study Room,Servant Room,Store Room
112                           Pooja Room,Servant Room
113                                 Pooja Room,Others
114                                      Servant Room
116     Study Room,Pooja Room,Servant Room,Store Room
117                                     not available
118                Study Room,Pooja Room,Servant Room
119     Pooja Room,Study Room,Servant Room,Store Room
120                Pooja Room,Study Room,Servant Room
121                                     not available
122                                     not available
123                                     not available
124                                     not available
125                                     not available
126                                      Servant Room
127         Pooja Room,Study Room,Servant Room,Others
128                           Study Room,Servant Room
129     Pooja Room,Study Room,Servant Room,Store Room
130                                      Servant Room
131                Pooja Room,Study Room,Servant Room
132                                      Servant Room
133                                      Servant Room
134                                            Others
135                                        Store Room
136                                      Servant Room
137                                      Servant Room
138                                      Servant Room
139     Pooja Room,Store Room,Study Room,Servant Room
140                           Study Room,Servant Room
141                                     not available
142                           Study Room,Servant Room
143                                 Pooja Room,Others
144                                            Others
145                                            Others
146                                 Pooja Room,Others
147                                            Others
148                                            Others
149                                            Others
150                               Servant Room,Others
151                                      Servant Room
152                                      Servant Room
153                                            Others
154                                     not available
155                Study Room,Servant Room,Pooja Room
156                                            Others
157                                            Others
158                                      Servant Room
159                                      Servant Room
160                                        Pooja Room
161         Pooja Room,Study Room,Servant Room,Others
162                Pooja Room,Study Room,Servant Room
163     Pooja Room,Store Room,Study Room,Servant Room
164                           Study Room,Servant Room
165                             Pooja Room,Store Room
166                                            Others
167                                        Study Room
168                                     not available
169                                     not available
170                      Pooja Room,Study Room,Others
171                                     not available
172                                     not available
173                                            Others
174                                        Study Room
175     Pooja Room,Study Room,Servant Room,Store Room
176     Study Room,Servant Room,Store Room,Pooja Room
177                                     not available
178                                     not available
179                               Servant Room,Others
180                                            Others
181                                        Pooja Room
182                                        Pooja Room
183                                     not available
184                                     not available
185                                     not available
186                                     not available
187                                     not available
188                                     not available
189                                     not available
190                             Pooja Room,Study Room
191                                     not available
192                Study Room,Servant Room,Pooja Room
193                                     not available
194                                     not available
195                                     not available
196                                     not available
197                                     not available
198                                     not available
199                                     not available
200                                     not available
201                                     not available
202                                     not available
203                                     not available
204         Pooja Room,Study Room,Servant Room,Others
205                             Pooja Room,Study Room
206                                     not available
207                                     not available
208                                     not available
209                                     not available
210                                     not available
211                                     not available
212                                     not available
213                                        Pooja Room
214                                     not available
215     Pooja Room,Study Room,Servant Room,Store Room
216                                     not available
217                                     not available
218                                     not available
219                                     not available
220                                     not available
221                                     not available
222                                        Pooja Room
223                                        Store Room
224                                     not available
225                           Pooja Room,Servant Room
226                                     not available
227                                     not available
228         Pooja Room,Study Room,Servant Room,Others
229                                      Servant Room
230                                     not available
231                                     not available
232                                     not available
233                                     not available
234                                     not available
235                                     not available
236                                     not available
237                                     not available
238                                     not available
239                                     not available
240                                     not available
241                                     not available
242                                        Pooja Room
243                                            Others
244                                     not available
245                                     not available
246                                     not available
247                                      Servant Room
248                                     not available
249                                     not available
250                                     not available
251                                     not available
252                               Servant Room,Others
253                                            Others
254                                     not available
255                                     not available
256                                     not available
257                                            Others
258                                     not available
259                                     not available
260                                     not available
261                                     not available
262                                     not available
263                                     not available
264                                     not available
265                                     not available
266                                     not available
267                                     not available
268                                     not available
269                                     not available
270                                     not available
271                                     not available
272                                     not available
274                                        Pooja Room
275                                     not available
276                                     not available
279                                     not available
280                                            Others
281                                     not available
282                                     not available
283                                     not available
285                                      Servant Room
286                                        Pooja Room
287                                     not available
288                                     not available
289                                     not available
290                                     not available
291                                     not available
297                                     not available
298                                     not available
299                                     not available
300                                     not available
301                                     not available
302                                     not available
303                                            Others
304                Pooja Room,Study Room,Servant Room
305                                     not available
306                                            Others
307                                            Others
308                                     not available
309                                     not available
310                                     not available
311                                     not available
312                                     not available
313                                     not available
314                                     not available
315                                     not available
316                                     not available
317                                     not available
322                                     not available
323                                     not available
327                                     not available
328                                     not available
329                                     not available
330                                     not available
331                                     not available
332                                     not available
333                                     not available
334                                     not available
335                             Pooja Room,Study Room
336                                     not available
337                                        Pooja Room
338                                     not available
339                                     not available
340                                        Pooja Room
341                                     not available
342                                     not available
343                                     not available
344                                     not available
345                                     not available
346                                     not available
347                                     not available
348                                     not available
349                                        Pooja Room
350                                     not available
351                                            Others
352                                     not available
353                Pooja Room,Study Room,Servant Room
354                                     not available
355                                     not available
356                                     not available
357                                     not available
358                                     not available
359                                     not available
360                                     not available
361                                     not available
362                                     not available
363         Pooja Room,Study Room,Servant Room,Others
364                                     not available
365                                     not available
366                                            Others
367                                     not available
368                                     not available
369                                     not available
370                                            Others
371                                     not available
372                                     not available
373                    Pooja Room,Servant Room,Others
374                             Pooja Room,Study Room
375                                     not available
376                                     not available
377                                     not available
378                                     not available
379                                     not available
380                                     not available
381                             Pooja Room,Store Room
382                                            Others
383                                        Store Room
384                                     not available
385                           Servant Room,Store Room
386                                     not available
387                           Servant Room,Study Room
388                                     not available
389                                     not available
390                                            Others
391                                     not available
392                                            Others
393                                     not available
394                                            Others
395                                      Servant Room
396                                     not available
397                                     not available
398                                            Others
399                                 Study Room,Others
400                                     not available
401                                     not available
402         Pooja Room,Study Room,Servant Room,Others
403                                     not available
404                                     not available
405                      Pooja Room,Study Room,Others
406                                     not available
407                                     not available
408                                     not available
409                                     not available
410                                     not available
411                                     not available
412                                      Servant Room
413                                     not available
414                                     not available
415                                     not available
416                                     not available
417                                 Pooja Room,Others
418                                            Others
419                                     not available
420         Pooja Room,Study Room,Servant Room,Others
421                                     not available
422                                     not available
423                                     not available
424                                            Others
425                                     not available

In [67]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [68]:
df['noOfFloor'].value_counts()

noOfFloor
3 Floors     304
2 Floors     294
1 Floors     183
4 Floors     138
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
12 Floors      2
10 Floors      2
11 Floors      2
02 Floors      1
21 Floors      1
27 Floors      1
13 Floors      1
20 Floors      1
41 Floors      1
51 Floors      1
16 Floors      1
33 Floors      1
Name: count, dtype: int64

In [69]:
df['noOfFloor'].isnull().sum()

np.int64(19)

In [70]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)

In [71]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [72]:
df['facing'].fillna('NA',inplace=True)

C:\Users\ARCHIT\AppData\Local\Temp\ipykernel_30692\3692945726.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['facing'].fillna('NA',inplace=True)

0       North-East
1               NA
2             West
3            North
4             West
5             East
6             East
7               NA
8       North-East
9             West
10            West
11           North
12           North
13           North
14            West
15            East
16      South-West
17      North-East
18           South
19           North
20            West
21      North-East
22              NA
23            East
24            East
25      North-East
26      South-East
27      North-East
28      North-West
29              NA
30            East
31           North
32            East
33      North-East
34              NA
35      South-East
36      North-East
37           North
38            East
39           North
40           North
41            East
42      South-East
43      North-West
44            West
45      North-East
46            East
47            East
48           North
49           North
50           South
51      South-West
52      North-East
53      South-East
54            East
55           South
56           North
57              NA
58            East
59            East
60      North-East
61           North
64              NA
65      South-East
79              NA
80            East
90      North-East
91      North-East
101     South-East
106     South-East
107     North-East
108          North
109          North
112           East
113          South
114     South-East
116           East
117           East
118           West
119     North-West
120     North-East
121           East
122     North-West
123     North-West
124     North-West
125     North-West
126     North-East
127          North
128           East
129           East
130     North-West
131           West
132           West
133     South-West
134     North-East
135          North
136           East
137           East
138     North-East
139          North
140           East
141           West
142     North-East
143           East
144          South
145          North
146           West
147     South-East
148     South-East
149          South
150     South-West
151          North
152     North-East
153     North-East
154          South
155           East
156           West
157     South-West
158           West
159     North-East
160     North-East
161           East
162     North-East
163     North-East
164           East
165          North
166           East
167     North-East
168             NA
169           East
170             NA
171             NA
172     North-East
173     North-East
174          North
175     South-West
176     North-West
177             NA
178             NA
179     North-East
180     North-East
181     South-West
182           East
183             NA
184             NA
185     South-East
186             NA
187           East
188             NA
189             NA
190          South
191             NA
192     North-East
193          North
194             NA
195             NA
196             NA
197           East
198             NA
199             NA
200             NA
201             NA
202             NA
203             NA
204             NA
205             NA
206             NA
207             NA
208     North-East
209             NA
210             NA
211           West
212          South
213     North-East
214          South
215           East
216     North-East
217             NA
218             NA
219             NA
220           East
221           East
222     North-East
223     South-East
224           East
225           East
226             NA
227             NA
228          North
229     North-East
230             NA
231          North
232             NA
233             NA
234             NA
235             NA
236             NA
237             NA
238             NA
239             NA
240             NA
241             NA
242           East
243     South-West
244             NA
245             NA
246             NA
247           East
248             NA
249          South
250           East
251           East
252          North
253           East
254             NA
255             NA
256             NA
257             NA
258             NA
259             NA
260             NA
261             NA
262             NA
263             NA
264             NA
265             NA
266           East
267             NA
268             NA
269             NA
270          South
271             NA
272     North-East
274     South-East
275           East
276          North
279             NA
280     North-East
281           East
282          North
283             NA
285          North
286             NA
287             NA
288             NA
289     North-West
290          North
291             NA
297             NA
298          North
299             NA
300             NA
301             NA
302             NA
303     South-East
304             NA
305             NA
306             NA
307             NA
308             NA
309             NA
310             NA
311             NA
312             NA
313     North-East
314             NA
315             NA
316             NA
317             NA
322             NA
323             NA
327             NA
328             NA
329     North-East
330             NA
331             NA
332             NA
333          North
334             NA
335     South-West
336     South-East
337          North
338             NA
339             NA
340           East
341             NA
342     South-East
343     North-East
344             NA
345             NA
346             NA
347           East
348           East
349     North-East
350             NA
351             NA
352           West
353     South-East
354             NA
355             NA
356             NA
357           West
358             NA
359             NA
360     North-East
361             NA
362             NA
363          South
364             NA
365           East
366          North
367           West
368             NA
369             NA
370             NA
371             NA
372             NA
373          North
374             NA
375             NA
376     North-East
377             NA
378             NA
379             NA
380             NA
381           East
382           West
383             NA
384             NA
385          North
386             NA
387             NA
388             NA
389           East
390     South-West
391           West
392             NA
393             NA
394     South-East
395             NA
396             NA
397          North
398     South-East
399             NA
400             NA
401     North-West
402     North-West
403             NA
404          North
405     North-East
406             NA
407             NA
408           East
409     North-East
410             NA
411             NA
412             NA
413             NA
414           East
415             NA
416     South-West
417          North
418           East
419     South-East
420           East
421           West
422             NA
423             NA
424             NA
425           West
426             NA
427           East
428     North-West
429             NA
430          North
431          South
432     North-East
433             NA
434             NA
435     North-West
436             NA
437     North-West
438     North-East
439             NA
440     North-East
441     South-East
442     North-West
443             NA
444          North
445     North-East
446             NA
447             NA
448     North-East
449           East
450          South
451     South-East
452             NA
453             NA
454             NA
455           East
456     North-East
457           East
458             NA
459             NA
460     North-East
461          South
462          South
463             NA
464           West
465          North
466          South
467          North
468             NA
469             NA
470             NA
471             NA
472             NA
473     North-West
474             NA
475             NA
476             NA
477             NA
478             NA
479             NA
480             NA
481           East
482          North
483             NA
484     North-East
485             NA
486           East
487             NA
488           East
489             NA
490           East
491             NA
492             NA
493          North
494             NA
495             NA
496          North
497             NA
498             NA
499             NA
500           East
501             NA
502             NA
503          North
504     North-East
505          North
506           East
507             NA
508     North-East
509             NA
510             NA
511             NA
512     South-East
513             NA
514           West
515             NA
516           West
517          North
518     South-West
519     North-East
520             NA
521     North-East
522             NA
523             NA
524     South-East
525          South
526             NA
527           East
528     North-East
529          South
530          South
531             NA
532             NA
533             NA
534           East
535           East
536             NA
537             NA
538             NA
539             NA
540          North
541             NA
542             NA
543          South
544             NA
545             NA
546     North-East
547             NA
548             NA
549     North-East
550             NA
551           East
552           West
553          North
554           East
555             NA
556             NA
557             NA
558     South-West
559             NA
560             NA
561             NA
562             NA
563          North
564             NA
565          North
566             NA
567             NA
568             NA
569             NA
570             NA
571             NA
572             NA
573             NA
574             NA
575     North-East
576     North-West
577             NA
578             NA
579           East
580           East
581     North-East
582             NA
583             NA
584     North-East
585             NA
586             NA
587           East
588     North-East
589             NA
590          North
591             NA
592           East
593             NA
594             NA
595             NA
596             NA
597             NA
598             NA
599          North
600             NA
601             NA
602     North-West
603             NA
604     South-East
605           East
606             NA
607             NA
608     South-East
609             NA
610           East
611     North-West
612           East
613     North-East
614           West
615           East
616           East
617     North-West
618             NA
619             NA
620     North-East
621             NA
622     North-East
623             NA
624             NA
625           East
626             NA
627           East
628     South-West
629           West
630             NA
631             NA
632          North
633           West
634     South-East
635     North-East
636          North
637             NA
638           East
639           West
640             NA
641          North
642          North
643             NA
644             NA
645           East
646           East
647           East
648     North-East
649          North
650           East
651          North
652           West
653     North-East
654             NA
655     North-East
656             NA
657     North-West
658           East
659           West
660           West
661     North-East
662           East
663           East
664             NA
665          South
666             NA
667             NA
668           East
669           East
670     South-East
671           West
672     North-West
673             NA
674          South
675     North-East
676     North-West
677             NA
678     North-East
679           East
680           East
681           East
682     North-East
683           East
684           East
685     North-West
686           East
687             NA
688     North-East
689             NA
690     North-West
691           East
692           East
693          North
694     North-East
695          North
696          North
697           East
698          North
699     North-East
700     North-East
701           West
702     North-East
703     North-East
704     North-East
705             NA
706             NA
707           East
708          South
709           East
710     North-West
711     North-West
712           West
713     North-East
714             NA
715          North
716             NA
717          North
718     North-West
719             NA
720           East
721     South-West
722           East
723     North-East
724           East
725             NA
726          North
727             NA
728     North-East
729     North-East
730           East
731     North-East
732     North-East
733           East
734           East
735           East
736     South-East
737             NA
738           East
739           West
740           West
741     North-East
742     North-West
743          South
744     South-East
745          North
746           East
747           West
748           East
749          North
750           East
751           West
752           East
753     North-East
754     North-East
755           East
756     North-East
757     North-East
758     South-West
759           East
760           West
761          North
762     North-East
763           East
764     North-East
765          North
766           East
767     North-East
768             NA
769     North-East
770     North-East
771           West
772          North
785           West
786     North-East
787          South
788           East
789     North-West
790           East
791     North-East
792          North
793             NA
794             NA
795     South-East
796           West
797     North-East
798           East
799          North
800           East
801           East
802           East
803     North-West
804     North-East
805     North-East
806             NA
807          North
808             NA
809           East
810             NA
811          North
812     North-East
813          North
814           East
815     North-East
816           East
817             NA
818             NA
819             NA
820             NA
821     North-East
822     North-West
823     South-West
825           West
826           West
827           East
828     North-East
829     North-East
830           West
831           East
832     North-East
833     North-East
834             NA
835          North
836          North
837     North-West
838     North-East
839           East
840     North-West
841          North
842           East
843     North-East
844     South-East
845           West
846     North-East
848           West
849           East
850     North-East
851     North-West
852             NA
853     North-West
854             NA
855          North
856     South-West
857             NA
858     North-East
859     North-West
860           East
861           East
862          North
863          North
864     South-East
865          South
866           West
867          South
868     North-East
869          North
870           East
871           East
872           East
873     North-East
874           East
875     North-East
876     North-East
877     South-West
878     North-East
879           West
880           East
881          North
882     North-East
883           West
884           West
885     North-East
886           East
887     South-West
888          South
889     North-East
890             NA
891          North
892             NA
893           East
894           East
895     North-East
896     North-East
897           West
898             NA
899     North-East
900     North-East
901          North
902           East
903     North-East
904           East
905             NA
906     North-East
907           West
908           West
909     North-West
910           West
911     North-East
912          North
913           East
914           East
915     North-East
916           West
917           East
918     North-East
919     North-East
920           West
921           East
922             NA
923           East
924          South
925     North-East
926     North-East
927     North-East
928     North-East
929     North-East
930          North
931          South
932     South-West
933          North
934     North-East
935          North
936           East
937           East
938           East
939          North
940           East
941           East
942           East
943          North
944          North
945          North
946          North
947          North
948     South-East
949           East
950          North
951     North-East
952     North-East
953     North-West
954           East
955     North-East
956     South-West
957           West
958           East
959             NA
960          South
961           West
962           West
963             NA
964             NA
965          North
966           West
967     South-East
968           West
969           West
970           East
971          North
972     North-East
973          North
974           West
975             NA
976           West
977          North
978     North-East
979           East
980          North
981           East
982           West
983          North
984           West
985           East
986           East
987     North-East
988             NA
989          North
990     North-East
991     North-East
992           East
993           East
994     North-East
995     South-East
996     North-East
997           West
998     North-East
999     North-East
1000         North
1001    North-East
1002          West
1003          West
1004          East
1005            NA
1006          East
1007          East
1008          East
1009          East
1010    North-West
1011          East
1012         North
1013    South-East
1014         South
1015            NA
1016          East
1017            NA
1018          West
1019    North-East
1020            NA
1021          West
1022          East
1023         North
1024            NA
1025          East
1026          East
1027          East
1028    North-East
1029    North-East
1030    South-East
1031    North-West
1032    South-West
1033    South-West
1034    North-West
1035    South-East
1036    North-East
1037    North-West
1038            NA
1039    North-East
1040         North
1041          East
1042          West
1043            NA
Name: facing, dtype: str

In [73]:
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

In [74]:
df.insert(loc=1,column='property_type',value='house')

In [75]:
df.shape

(974, 20)

In [76]:
df.info()

<class 'pandas.DataFrame'>
Index: 974 entries, 0 to 1043
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    974 non-null    str
 1   property_type    974 non-null    str
 2   society          974 non-null    str
 3   price            974 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     974 non-null    str
 7   bedRoom          974 non-null    int64
 8   bathroom         974 non-null    int64
 9   balcony          974 non-null    object
 10  additionalRoom   578 non-null    str
 11  address          969 non-null    str
 12  floorNum         955 non-null    object
 13  facing           662 non-null    str
 14  agePossession    974 non-null    str
 15  nearbyLocations  851 non-null    str
 16  description      974 non-null    str
 17  furnishDetails   732 non-null    str
 18  features         662 non-null    str
 19  rating           852 non-null    str
dtypes: float64(3), int64(2), object(2), str(13)
memory usage: 159.8+ KB

In [77]:
df.to_csv('house_cleaned.csv',index=False)