In [4]:
import numpy as np 
import pandas as pd

In [5]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [99]:
df=pd.read_csv('flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2355,3 BHK Flat in Sector 63A Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Birla Navya,3.23 Crore,"₹ 26,875/sq.ft.",Super Built up area 2150(199.74 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"H-42, 4th Floor, Amoda, Sector 63A Gurgaon, Gu...",4th of 4 Floors,West,Within 3 months,"['Sector 54 Chowk Metro Station', 'WorldMark G...",This is a premium 3 bhk+utility+terrace proper...,"['6 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Environment4 out of 5', 'Lifestyle4 out of 5...",A69419710
1989,2 BHK Flat in Sector 99 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Pivotal Riddhi Siddhi,40 Lac,"₹ 4,444/sq.ft.",Super Built up area 900(83.61 sq.m.)Carpet are...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 99 Gurgaon, Gurgaon, Haryana",9th of 14 Floors,NaN,0 to 1 Year Old,"['Huda Metro Station', 'The Hive Mall', 'JMS M...",1) the flat is in tower 8 and on ninth floor\n...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4.5 out of 5', 'Lifestyle4 out of...",G53211690
137,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,GLS Avenue 51,42 Lac,"₹ 7,106/sq.ft.",Carpet area: 591 (54.91 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,"Pooja Room,Study Room","Sector 92 Gurgaon, Gurgaon, Haryana",4th of 12 Floors,East,1 to 5 Year Old,"['Yaduvanshi Shiksha Niketan Sector- 92', 'Aar...",East facing property with great view,"['1 Fan', '1 Exhaust Fan', '2 Geyser', '1 Ligh...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Safety3 out of 5', ...",I68531730
2820,3 BHK Flat in Sector 37D Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Ramprastha Primera,1.02 Crore,"₹ 6,000/sq.ft.",Super Built up area 1700(157.94 sq.m.),3 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",22nd of 23 Floors,NaN,Under Construction,"['JMS Marine Square Mall', 'HUDA Market', 'Dwa...",Residential apartment for sell.The property ha...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",Q67217474
1602,3 BHK Flat in Sector 82 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Mapsko Royale Ville3.7 ★,1.12 Crore,"₹ 8,000/sq.ft.",Super Built up area 1790(166.3 sq.m.)Built Up ...,3 Bedrooms,4 Bathrooms,2 Balconies,"Pooja Room,Servant Room","000, Sector 82 Gurgaon, Gurgaon, Haryana",6th of 18 Floors,North-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Golf Course Ext Rd', ""St...",Mapsko royale ville is one of gurgaon's most s...,"['4 Fan', '1 Exhaust Fan', '7 Light', '1 Modul...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction3 out ...",Q69680836

In [100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3017 non-null   str
 1   link             3017 non-null   str
 2   society          3016 non-null   str
 3   price            3007 non-null   str
 4   area             3004 non-null   str
 5   areaWithType     3008 non-null   str
 6   bedRoom          3008 non-null   str
 7   bathroom         3008 non-null   str
 8   balcony          3008 non-null   str
 9   additionalRoom   1694 non-null   str
 10  address          3002 non-null   str
 11  floorNum         3006 non-null   str
 12  facing           2127 non-null   str
 13  agePossession    3007 non-null   str
 14  nearbyLocations  2913 non-null   str
 15  description      3008 non-null   str
 16  furnishDetails   2203 non-null   str
 17  features         2594 non-null   str
 18  rating           2676 non-null   str
 19  property_id      3008 non-null   str
dtypes: str(20)
memory usage: 471.5 KB

In [101]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [102]:
df.drop(columns=['link','property_id'],inplace=True)

In [176]:
df.head(5)

,property_name,property_type,society,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_crore
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",0.45
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",0.50
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",0.40
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,1.47
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",0.70

In [104]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [105]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Orchard                                  32
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
DLF New Town Heights 13.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Experion The Heartsong3.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Bestech Park View Residency3.9 ★                     23
ATS Triumph3.9 ★                                     22
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Supertech Araville                                   18
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Ambience Creacions                                   18
Indiabulls Centrum Park3.7 ★                         18
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
M3M Golfestate4.4 ★                                  17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
M3M Skywalk                                          17
Conscient Heritage Max4.3 ★                          17
Godrej Summit3.7 ★                                   17
HCBS Sports Ville3.6 ★                               16
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
Godrej Oasis3.9 ★                                    15
Ansal Heights 86                                     15
Umang Monsoon Breeze                                 15
Emaar MGF The Palm Drive4.1 ★                        15
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
Ireo Victory Valley4.1 ★                             14
The Close North4.0 ★                                 14
Orchid Petals4.1 ★                                   14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Imperia The Esfera                                   14
Corona Optus3.9 ★                                    14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Ireo The Corridors                                   13
Breez Global Hill View                               11
M3M Soulitude                                        11
Godrej Aria3.8 ★                                     11
Raheja Vedaanta3.6 ★                                 11
Adani M2K Oyster Grande3.9 ★                         11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Alpha Corp GurgaonOne 844.0 ★                        11
DLF The Skycourt4.2 ★                                11
Godrej Air                                           10
Pivotal Devaan                                       10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Pyramid Urban Homes 2                                10
Zara Aavaas                                          10
Ramprastha The Edge Towers3.5 ★                      10
DLF New Town Heights 24.0 ★                          10
ATS Kocoon                                           10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Signature Global Synera3.4 ★                         10
ILD Greens4.1 ★                                       9
Pareena Mi Casa                                       9
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Altura                                        8
M3M Skycity                                           8
GLS Avenue 51                                         8
Assotech Blith                                        8
M3M Capital                                           8
Emaar Digihomes                                       8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Tulip Ivory3.5 ★                                      8
Vatika Lifestyle Homes3.8 ★                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Birla Navya                                           8
Emaar Imperial Gardens3.8 ★                           7
Mapsko Casa Bella3.8 ★                                7
Sare Crescent Parc Royal Greens Phase 1               7
Signature Global City                                 7
Ansal Housing Highland Park                           7
Trisara Our Homes 3                                   7
AIPL Zen Residences                                   7
Orris Carnation Residency3.7 ★                        7
Sare Green ParC Phase 3                               7
Ireo The Grand Arch4.0 ★                              7
Signature Andour Heights3.8 ★                         7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Supertech Hues                                        6
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Greenopolis                                           6
Hero Homes                                            6
Suncity Vatsal Valley                                 6
Sidhartha NCR One Phase 14.2 ★                        6
Signature Global Park 4                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Mapsko Royale Ville3.7 ★                              6
Kiran Residency                                       6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Pyramid Urban                                         6
M3M Sierra 68                                         6
Pioneer Araya3.8 ★                                    6
BPTP Astaire Gardens3.7 ★                             6
Shapoorji Pallonji Joyville Gurugram                  6
Apna Enclave                                          5
Signature Global City 81                              5
Godrej Habitat                                        5
Silverglades The Melia                                5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Central Park Flower Valley Aqua Front Towers          5
Green Court3.7 ★                                      5
Ashiana Anmol3.5 ★                                    5
Signature Global the Millennia                        5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Central Park Resorts4.4 ★                             5
DLF Regency Park 24.0 ★                               5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Emaar MGF Emerald Estate3.8 ★                         5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Ireo Uptown4.1 ★                                      5
Signature Global Grand IVA3.9 ★                       5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
ATS Marigold                                          5
Conscient Elevate                                     5
Krisumi Waterfall Residences                          5
Essel Towers                                          5
Vatika Sovereign Park                                 5
Ramprastha Skyz                                       4
Signature The Serenas                                 4
DLF New Town Heights3.7 ★                             4
Lotus Homz4.0 ★                                       4
Unitech Vistas                                        4
ILD Grand                                             4
Global Hill View                                      4
Railway Officers RPF Society                          4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Orris Aster Court                                     4
Godrej Icon                                           4
Unitech Fresco3.8 ★                                   4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Godrej Frontier3.7 ★                                  4
Ramprastha Primera                                    4
Sare Petioles                                         4
Corona Gracieux                                       4
Vatika Xpressions                                     3
Raheja Revanta                                        3
Adani Aangan Arcade                                   3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Maxworth City Residences                              3
Deepak Minda                                          3
Unitech The Residences3.7 ★                           3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Bestech Park View City 23.9 ★                         3
AFNHB Jalvayu Vihar3.7 ★                              3
Pyramid Elite                                         3
Brisk Lumbini Terrace Homes                           3
My Home                                               3
Essel Tower                                           3
Krrish Florence Estate                                3
Piedmont Taksila heights3.6 ★                         3
Tulip White3.5 ★                                      3
Sapphire Eighty Three                                 3
DLF The Grove                                         3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Carlton Estate4.0 ★                               3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
Unitech Heritage City                                 3
Paras Quartier                                        3
Ambience Lagoon3.9 ★                                  3
Unitech Uniworld Gardens3.8 ★                         3
Raheja Atharva3.6 ★                                   3
Tulip Purple                                          3
Vatika Independent Floors3.8 ★                        3
Shree Arihant Apartment                               3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Puri Diplomatic Greens3.9 ★                           3
Sunischit Apartments                                  3
Dhoot Time Residency4.0 ★                             3
ATS Kocoon4.2 ★                                       3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Apex Our Homes                                        3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Kendriya Vihar4.1 ★                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
Unitech Sunbreeze                                     3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Spaze Privvy The Address3.9 ★                         3
Shri Ram Apartments                                   3
Tulip Petals3.6 ★                                     3
Sidhartha NCR Greens4.3 ★                             3
Valley View Estate                                    3
The Roselia 2                                         3
Satya Element One                                     3
DLF Royalton Tower                                    3
Smriti Apartment                                      3
Tulsiani Easy in Homes                                2
BPTP Freedom Park Life4.0 ★                           2
Puri The Aravallis                                    2
Ramprastha City                                       2
Ardee City3.8 ★                                       2
Supertech Hilltown                                    2
Raheja Vanya                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
M3M Urbana                                            2
Ansal Heights3.2 ★                                    2
Suncity Heights3.7 ★                                  2
Ramprastha The Atrium3.4 ★                            2
Today Callidora                                       2
Park Royal Apartment                                  2
Mapsko Paradise3.9 ★                                  2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Unitech Uniworld Gardens 23.4 ★                       2
Maruti Vihar                                          2
Vasant Appartments                                    2
Landmark The Residency                                2
Mahindra Luminare4.0 ★                                2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Pioneer Urban Presidia                                2
M3M Latitude                                          2
Ansal API Celebrity Suites                            2
CGHS Airport Apartment                                2
Bestech Spa Signature                                 2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
DLF The Icon3.7 ★                                     2
Professors Enclave CGHS                               2
BPTP Mansions Park Prime                              2
Paras Irene3.7 ★                                      2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Emaar MGF The Enclave                                 2
Vipul Belmonte3.9 ★                                   2
Bestech Park View Sanskruti4.1 ★                      2
M3M Ikonic                                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Viridian The Plaza 106                                2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Signature Global The Millennia 3                      2
M3M Sky Lofts                                         2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Central Park 2 Bellevue                               2
Tulip Orange3.9 ★                                     2
Adani Aangan Galleria                                 2
HCBS Sports Ville                                     2
Housing Board Colony                                  2
Sahara Grace                                          2
Aqua Front Towers                                     2
Oriental Valley CHS                                   2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Godrej Nature Plus Serenity                           2
Ashiana Anmol                                         2
Ganga Apartment                                       2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
Samaspurkunj                                          2
om appartments                                        2
Lavanya Apartments                                    2
Apartment                                             2
Vipul World Floors                                    2
Milan CGHS 9                                          2
Element One Service                                   2
Breeze Global Heights                                 2
Shapoorji Pallonji Joyville                           2
Dlf City                                              2
Silverglades Hightown Residences                      2
Surendra Avenue 69                                    2
Ambience Caitriona                                    2
Bhagwati Sadan                                        2
Sidhivinayak Apartments                               2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
maa bhagwati residency                                1
Parkwood Westend                                      1
Signature Global Infinity Mall                        1
The Cocoon                                            1
Godrej                                                1

In [106]:
df['society'].value_counts().shape

(638,)

In [107]:
import re

df['society'] = df['society'].apply(
    lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()
).str.lower()

In [108]:
df['society'].value_counts().shape

(604,)

In [109]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
smart world orchard                              32
smart world gems                                 32
emaar mgf emerald floors premier                 32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
la vida by tata housing                          28
signature global solera                          28
godrej nature plus                               27
bptp terra                                       25
emaar gurgaon greens                             25
eldeco accolade                                  24
experion the heartsong                           24
vatika gurgaon                                   24
bestech park view residency                      23
ats triumph                                      22
m3m heights                                      22
tata primanti                                    22
emaar palm gardens                               22
godrej                                           21
rof ananda                                       21
sare crescent parc                               21
experion windchants                              20
sare homes                                       19
antriksh heights                                 19
hcbs sports ville                                18
supertech araville                               18
sobha city                                       18
m3m golfestate                                   18
chd avenue                                       18
ambience creacions                               18
indiabulls centrum park                          18
ats tourmaline                                   18
m3m skywalk                                      18
mapsko mount ville                               18
gls arawali homes                                17
pareena coban residences                         17
conscient heritage max                           17
godrej summit                                    17
m3m merlin                                       16
bestech park view grand spa                      16
ramsons kshitij                                  15
godrej oasis                                     15
ansal heights 86                                 15
umang monsoon breeze                             15
emaar mgf the palm drive                         15
dlf the skycourt                                 15
dlf the primus                                   14
umang winter hills                               14
mvn athens                                       14
indiabulls enigma                                14
ireo victory valley                              14
the close north                                  14
orchid petals                                    14
ireo skyon                                       14
bestech park view ananda                         14
vatika the seven lamps                           14
imperia the esfera                               14
corona optus                                     14
central park flower valley                       13
puri emerald bay                                 13
ats kocoon                                       13
puri diplomatic greens                           13
ireo the corridors                               13
breez global hill view                           11
dlf regency park                                 11
m3m soulitude                                    11
godrej aria                                      11
breez global heights                             11
raheja vedaanta                                  11
adani m2k oyster grande                          11
tarc maceo                                       11
sbtl caladium                                    11
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
ild greens                                       10
godrej air                                       10
pivotal devaan                                   10
emaar mgf palm hills                             10
pyramid urban homes 2                            10
zara aavaas                                      10
ramprastha the edge towers                       10
capital residences 360                           10
signature global synera                          10
bestech park view city                            9
pareena mi casa                                   9
parsvnath green ville                             9
aipl the peaceful homes                           9
vatika city                                       9
microtek greenburg                                9
bestech altura                                    8
m3m skycity                                       8
gls avenue 51                                     8
assotech blith                                    8
m3m capital                                       8
emaar digihomes                                   8
orris aster court premier                         8
the lions cghs                                    8
tulip ivory                                       8
vatika lifestyle homes                            8
ss                                                8
avl 36 gurgaon                                    8
birla navya                                       8
emaar imperial gardens                            7
mapsko casa bella                                 7
sare crescent parc royal greens phase 1           7
signature global city                             7
ansal housing highland park                       7
trisara our homes 3                               7
ashiana anmol                                     7
aipl zen residences                               7
sidhartha ncr one phase                           7
orris carnation residency                         7
sare green parc phase 3                           7
ireo the grand arch                               7
signature andour heights                          7
signature global orchard avenue                   7
vipul lavanya                                     7
supertech hues                                    6
ashiana mulberry                                  6
signature global city 63a                         6
signature the roselia                             6
greenopolis                                       6
hero homes                                        6
green court                                       6
suncity vatsal valley                             6
signature global park 4                           6
hsiidc sidco aravali                              6
mapsko royale ville                               6
kiran residency                                   6
bestech park view spa next                        6
parsvnath exotica                                 6
pyramid urban                                     6
m3m sierra 68                                     6
pioneer araya                                     6
bptp astaire gardens                              6
apna enclave                                      5
signature global city 81                          5
godrej habitat                                    5
silverglades the melia                            5
pareena laxmi apartments                          5
satya the hermitage                               5
central park flower valley aqua front towers      5
signature global the millennia                    5
tulip monsella                                    5
m3m the marina                                    5
unitech uniworld gardens                          5
central park resorts                              5
signature global city 92                          5
pioneer park                                      5
emaar mgf emerald estate                          5
vatika city homes                                 5
unitech fresco                                    5
dlf park place                                    5
ireo uptown                                       5
signature global grand iva                        5
adani brahma samsara vilasa                       5
signature global city 37d ph 2                    5
ats marigold                                      5
conscient elevate                                 5
krisumi waterfall residences                      5
essel towers                                      5
vatika sovereign park                             5
ramprastha skyz                                   4
signature the serenas                             4
afnhb jalvayu vihar                               4
essel tower                                       4
lotus homz                                        4
unitech vistas                                    4
ild grand                                         4
global hill view                                  4
railway officers rpf society                      4
raheja navodaya                                   4
ss the coralwood                                  4
emaar palm heights                                4
krrish provence estate                            4
orris aster court                                 4
godrej icon                                       4
prime habitat                                     4
tata gurgaon gateway                              4
hsiidc sidco shivalik apartments                  4
godrej frontier                                   4
ramprastha primera                                4
kendriya vihar                                    4
dlf the arbour                                    4
sare petioles                                     4
corona gracieux                                   4
vatika xpressions                                 3
raheja revanta                                    3
adani aangan arcade                               3
sare green parc                                   3
chintels paradiso                                 3
maxworth city residences                          3
deepak minda                                      3
unitech the residences                            3
sidhartha ncr one                                 3
raheja sampada                                    3
pyramid elite                                     3
brisk lumbini terrace homes                       3
my home                                           3
bhagwati sadan                                    3
krrish florence estate                            3
piedmont taksila heights                          3
tulip white                                       3
sapphire eighty three                             3
dlf the grove                                     3
sukhshanti apartment                              3
ss almeria                                        3
dlf carlton estate                                3
dlf belvedere towers                              3
aipl club residences                              3
unitech heritage city                             3
paras quartier                                    3
ambience lagoon                                   3
raheja atharva                                    3
tulip purple                                      3
vatika independent floors                         3
shree arihant apartment                           3
mahindra aura                                     3
shri banke bihari society                         3
sunischit apartments                              3
dhoot time residency                              3
spaze privy                                       3
tulip lemon                                       3
conscient habitat                                 3
suncity platinum towers                           3
spaze privy at                                    3
apex our homes                                    3
guru gram haryana cghs                            3
siddhartha apartment                              3
whiteland blissville                              3
signature global solera 2                         3
pivotal riddhi siddhi                             3
unitech sunbreeze                                 3
sare green parc 2                                 3
dlf express greens                                3
spaze privvy the address                          3
shri ram apartments                               3
tulip petals                                      3
sidhartha ncr greens                              3
valley view estate                                3
the roselia 2                                     3
satya element one                                 3
dlf royalton tower                                3
smriti apartment                                  3
tulsiani easy in homes                            2
shree shyam residency                             2
bptp freedom park life                            2
puri the aravallis                                2
ramprastha city                                   2
ardee city                                        2
supertech hilltown                                2
raheja vanya                                      2
vatika inxt floors                                2
palam vihar society                               2
m3m urbana                                        2
ansal heights                                     2
suncity heights                                   2
ramprastha the atrium                             2
today callidora                                   2
park royal apartment                              2
mapsko paradise                                   2
mrg world ultimus                                 2
bptp pedestal                                     2
maruti vihar                                      2
vasant appartments                                2
landmark the residency                            2
mahindra luminare                                 2
the close south                                   2
lagoon apartment                                  2
elan the presidential                             2
pioneer urban presidia                            2
m3m latitude                                      2
ansal api celebrity suites                        2
cghs airport apartment                            2
bestech spa signature                             2
green campus chs                                  2
dlf the crest                                     2
dlf the icon                                      2
professors enclave cghs                           2
bptp mansions park prime                          2
paras irene                                       2
dlf the belaire                                   2
suncity avenue                                    2
bptp amstoria                                     2
emaar mgf the enclave                             2
vipul belmonte                                    2
m3m ikonic                                        2
the penthouses at the hibiscus                    2
ss hibiscus                                       2
viridian the plaza 106                            2
tulip leaf                                        2
vatika emilia floors                              2
emaar mgf palm studios                            2
orchid island                                     2
signature global the millennia 3                  2
m3m sky lofts                                     2
rof aalayas                                       2
awho shanti vihar                                 2
ansal api esencia                                 2
shyam apartment                                   2
raheja atlantis                                   2
central park 2 bellevue                           2
tulip orange                                      2
adani aangan galleria                             2
housing board colony                              2
sahara grace                                      2
aqua front towers                                 2
oriental valley chs                               2
emaar mgf emerald floors                          2
nbcc heights                                      2
supertech hill town                               2
suncity avenue 76                                 2
godrej nature plus serenity                       2
ganga apartment                                   2
suposhaa smartworld orchard                       2
mittal surya vihar                                2
residency grand                                   2
ss residency                                      2
samaspurkunj                                      2
om appartments                                    2
lavanya apartments                                2
apartment                                         2
vipul world floors                                2
milan cghs 9                                      2
element one service                               2
breeze global heights                             2
shapoorji pallonji joyville                       2
dlf city                                          2
silverglades hightown residences                  2
surendra avenue 69                                2
ambience caitriona                                2
sidhivinayak apartments                           2
jammu and kashmir bank employees cghs             2
maa bhagwati residency                            1
parkwood westend                                  1
signature global infinity mall                    1
the cocoon                                        1
senate court                                      1
signature global orchard avenue 2                 1
the new people apartments                         1
the serenas                                       1
central park resort belgravia residences          1
apex builders                                     1
ompee k s residency                               1
bhawna cghs                                       1
ansal sushant lok ci                              1
godrej meridien                                   1
pooja apartment                                   1
gokuldham society, bahadurgarh                    1
4s aradhya homes                                  1
emaar mgf palm terraces                           1
anamika enclave                                   1
huda ashok vihar phase                            1
emaar palm premier                                1
conscient one                                     1
not applicable                                    1
smartworld 1dxp                                   1
czar mahira homes 63a                             1
godrej summit premia towers                       1
m3m one key resiments                             1
sushant lok 1 builder floors                      1
vatika sovereign next sector-82 a gurgaon         1
micasa sec 68                                     1
shyam sadan                                       1
hanumanta apartment                               1
ashiyara 2                                        1
m3m golf hills phase 1                            1
abhinav group housing society                     1
signature signum 95a                              1
aardhya homesh                                    1
sonata group housing society sector 1 manesar     1
experion heartsong                                1
project krishna colony                            1
m3m antalya hills                                 1
malibu towne                                      1

In [110]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [111]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
40 Lac              29
2.5 Crore           29
60 Lac              29
45 Lac              26
2.1 Crore           26
65 Lac              25
1.85 Crore          23
2.35 Crore          23
35 Lac              23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
2.15 Crore          14
3.4 Crore           14
2.45 Crore          14
3.25 Crore          13
82 Lac              13
78 Lac              13
2.7 Crore           13
38 Lac              13
1.32 Crore          13
92 Lac              13
42 Lac              12
2.8 Crore           12
1.95 Crore          12
1.42 Crore          12
5 Crore             12
Price on Request    11
25 Lac              11
32 Lac              11
88 Lac              11
1.08 Crore          11
28 Lac              10
26 Lac              10
87 Lac              10
1.28 Crore          10
2.55 Crore          10
1.78 Crore          10
1.12 Crore          10
2.85 Crore           9
99 Lac               9
22 Lac               9
36 Lac               9
2.05 Crore           9
4 Crore              9
3.45 Crore           9
1.68 Crore           9
1.72 Crore           9
86 Lac               8
3.2 Crore            8
56 Lac               8
2.75 Crore           8
27 Lac               8
4.25 Crore           8
1.18 Crore           8
1.54 Crore           8
6.5 Crore            8
6 Crore              8
1.76 Crore           8
98 Lac               8
1.26 Crore           8
48 Lac               8
20 Lac               8
1.99 Crore           7
79 Lac               7
46 Lac               7
1.29 Crore           7
2.9 Crore            7
39 Lac               7
72 Lac               7
97 Lac               7
3.7 Crore            7
1.27 Crore           7
1.36 Crore           7
3.3 Crore            7
1.19 Crore           7
1.02 Crore           7
96 Lac               6
1.01 Crore           6
43 Lac               6
3.35 Crore           6
54 Lac               6
4.1 Crore            6
71.5 Lac             6
1.49 Crore           6
3.9 Crore            6
1.98 Crore           6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.51 Crore           6
2.95 Crore           6
3.05 Crore           6
1.16 Crore           6
21 Lac               6
1.59 Crore           6
1.14 Crore           6
1.39 Crore           6
1.34 Crore           6
1.13 Crore           6
37 Lac               6
1.47 Crore           5
29 Lac               5
1.83 Crore           5
93 Lac               5
4.5 Crore            5
64 Lac               5
24 Lac               5
1.79 Crore           5
2.29 Crore           5
66 Lac               5
1.93 Crore           5
2.12 Crore           5
3.75 Crore           5
6.75 Crore           5
1.33 Crore           5
49 Lac               5
2.78 Crore           5
1.24 Crore           5
1.17 Crore           5
2.22 Crore           5
1.82 Crore           5
1.43 Crore           5
1.91 Crore           5
1.69 Crore           5
1.44 Crore           5
1.92 Crore           5
68 Lac               5
1.62 Crore           5
3.95 Crore           4
6.15 Crore           4
74 Lac               4
28.5 Lac             4
1.71 Crore           4
1.48 Crore           4
5.6 Crore            4
5.9 Crore            4
1.64 Crore           4
3.6 Crore            4
1.77 Crore           4
1.52 Crore           4
62 Lac               4
1.73 Crore           4
5.25 Crore           4
1.37 Crore           4
1.31 Crore           4
1.58 Crore           4
2.09 Crore           4
41.5 Lac             4
1.22 Crore           4
4.3 Crore            4
4.85 Crore           4
7 Crore              4
3.1 Crore            4
1.66 Crore           4
31 Lac               4
89 Lac               4
73 Lac               4
36.5 Lac             4
33 Lac               4
1.23 Crore           4
67 Lac               4
58 Lac               4
4.75 Crore           3
83 Lac               3
34 Lac               3
3.85 Crore           3
2.33 Crore           3
2.79 Crore           3
1.41 Crore           3
91 Lac               3
3.49 Crore           3
1.67 Crore           3
4.8 Crore            3
2.51 Crore           3
2.01 Crore           3
2.08 Crore           3
69 Lac               3
1.09 Crore           3
2.28 Crore           3
3.8 Crore            3
2.03 Crore           3
1.04 Crore           3
2.24 Crore           3
52 Lac               3
3.15 Crore           3
1.21 Crore           3
2.36 Crore           3
1.57 Crore           3
64.5 Lac             3
1.88 Crore           3
84 Lac               3
51 Lac               3
5.8 Crore            3
1.63 Crore           3
72.5 Lac             3
4.2 Crore            3
94 Lac               3
47 Lac               3
41 Lac               2
31.5 Lac             2
2.91 Crore           2
59 Lac               2
3.29 Crore           2
71 Lac               2
87.5 Lac             2
52.56 Lac            2
5.7 Crore            2
1.56 Crore           2
2.26 Crore           2
2.99 Crore           2
2.87 Crore           2
2.57 Crore           2
5.2 Crore            2
4.6 Crore            2
3.21 Crore           2
3.32 Crore           2
1.87 Crore           2
3.55 Crore           2
98.5 Lac             2
56.2 Lac             2
88.5 Lac             2
4.7 Crore            2
4.45 Crore           2
27.75 Lac            2
2.04 Crore           2
4.55 Crore           2
7.5 Crore            2
11 Crore             2
27.1 Lac             2
2.58 Crore           2
2.14 Crore           2
53 Lac               2
77.5 Lac             2
6.2 Crore            2
2.23 Crore           2
53.5 Lac             2
4.49 Crore           2
2.52 Crore           2
2.13 Crore           2
2.17 Crore           2
8.5 Crore            2
8 Crore              2
1.46 Crore           2
25.5 Lac             2
4.26 Crore           2
2.41 Crore           2
2.02 Crore           2
14 Crore             2
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
7.15 Crore           1
2.82 Crore           1
54.99 Lac            1
4.95 Crore           1
5.31 Crore           1
3.19 Crore           1
4.4 Crore            1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
55.5 Lac             1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
8.35 Crore           1
81 Lac               1
26.1 Lac             1
1.06 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
2.77 Crore           1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
9.3 Crore            1
1.74 Crore           1
4.21 Crore           1
4.16 Crore           1
4.52 Crore           1
1.84 Crore           1
8.44 Crore           1
13.2 Crore           1
2.92 Crore           1
2.38 Crore           1
97.5 Lac             1
2.64 Crore           1
2.49 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
49.5 Lac             1
16 Lac               1
2.86 Crore           1
86.92 Lac            1
94.99 Lac            1
88.4 Lac             1
3.72 Crore           1
57 Lac               1
95.5 Lac             1
96.07 Lac            1
19 Lac               1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
82.5 Lac             1
61 Lac               1
15 Crore             1
7.8 Crore            1
1.97 Crore           1
39.5 Lac             1
4.02 Crore           1
3.98 Crore           1
54.8 Lac             1
2.69 Crore           1
2.54 Crore           1
37.5 Lac             1
97.04 Lac            1
3.23 Crore           1
7.9 Crore            1
6.02 Crore           1
29.8 Lac             1
94.5 Lac             1
2.44 Crore           1
9 Crore              1
3.99 Crore           1
64.45 Lac            1
37.1 Lac             1
7.4 Crore            1
3.78 Crore           1
98.88 Lac            1
68.85 Lac            1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [112]:
df[df['price']=='Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1644,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1972,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2054,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2357,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2522,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2549,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2640,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2959,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2972,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2973,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [113]:
def convert_price(price):

    if pd.isna(price):
        return np.nan

    price = str(price)

    if "Crore" in price:
        return float(price.split()[0]) * 10000000

    elif "Lac" in price:
        return float(price.split()[0]) * 100000

    else:
        return np.nan

In [114]:
df['price_numeric'] = df['price'].apply(convert_price)

In [115]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

df['price_numeric'] = imputer.fit_transform(df[['price_numeric']])

In [116]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_numeric
2194,4 BHK Flat in Sector 70 Gurgaon,tulip ivory,2.35 Crore,"₹ 9,791/sq.ft.",Carpet area: 2400 (222.97 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"Sector 70 Gurgaon, Gurgaon, Haryana",8th of 12 Floors,West,5 to 10 Year Old,"['Reach 3 Roads Shopping Mall', 'Southern Peri...","Corner building, sun facing, cross ventilation...","['1 Light', '1 Wardrobe', 'No AC', 'No Bed', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area3.5 out of 5', 'Construction3.5 ou...",23500000.0
2652,1 BHK Flat in Sohna,mvn athens,24 Lac,"₹ 7,056/sq.ft.",Carpet area: 340.09 (31.6 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,NaN,"10/1204, Sohna, Gurgaon, Haryana",12nd of 14 Floors,West,1 to 5 Year Old,"['SBI ATM', 'Axis bank ATM', 'UCO bank ATM', '...",It has a huge balcony with great view and full...,"['2 Fan', '1 Dining Table', '1 Geyser', '3 Lig...","['Lift(s)', 'High Ceiling Height', 'Maintenanc...","['Green Area4 out of 5', 'Amenities4.5 out of ...",2400000.0
120,3 BHK Flat in Sector 63A Gurgaon,czar mahira homes 63a,42 Lac,"₹ 7,407/sq.ft.",Carpet area: 567 (52.68 sq.m.),3 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 63a, Sector 63A Gurgaon, Gurgaon, Haryana",Basement of 28 Floors,NaN,undefined,"['Metro World Mall', 'Omaxe Gurgaon Mall', 'Sa...",Best in class property available at sector 63a...,NaN,NaN,"['Environment4 out of 5', 'Safety5 out of 5', ...",4200000.0
1479,2 BHK Flat in Sector 79 Gurgaon,godrej,1.33 Crore,"₹ 8,531/sq.ft.",Super Built up area 1559(144.84 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Aa1, Sector 79 Gurgaon, Gurgaon, Haryana",6th of 15 Floors,North-West,1 to 5 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...",Godrej 101 is one of gurgaon's most sought aft...,NaN,"['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of...",13300000.0
1083,4 BHK Flat in Sector 69 Gurgaon,tulip violet,1.8 Crore,"₹ 8,955/sq.ft.",Super Built up area 2010(186.74 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,Pooja Room,"A7 908, Sector 69 Gurgaon, Gurgaon, Haryana",9th of 14 Floors,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This 4 bhk apartment is available for sale in ...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of...",18000000.0

In [117]:
def convert_to_crore(price):

    if pd.isna(price):
        return np.nan

    price = str(price)

    if "Crore" in price:
        return round(float(price.split()[0]),2)

    elif "Lac" in price:
        return round(float(price.split()[0]) / 100,2)

    else:
        return np.nan

In [118]:
df['price_crore'] = df['price'].apply(convert_to_crore)

In [119]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

df['price_crore'] = imputer.fit_transform(df[['price_crore']])

In [120]:
df['price_crore'].value_counts()

price_crore
1.25     79
1.10     61
0.90     60
1.40     60
1.20     59
1.50     59
1.30     57
0.95     55
2.00     51
1.75     47
1.00     46
1.60     43
1.35     41
1.55     40
1.90     40
0.75     38
1.65     38
1.80     37
0.80     37
1.70     37
2.20     34
0.50     33
1.15     33
0.85     32
0.40     31
1.45     31
1.05     30
2.50     29
0.60     29
0.65     28
0.45     26
2.10     26
1.37     25
0.35     24
1.85     23
2.35     23
0.55     22
3.00     22
0.70     21
2.25     20
0.30     19
3.50     19
2.40     18
2.30     18
0.28     17
2.65     16
0.78     15
1.38     15
0.88     15
2.60     15
0.82     14
0.32     14
2.15     14
0.38     14
3.40     14
2.45     14
0.42     13
3.25     13
2.70     13
0.26     13
0.36     13
1.32     13
0.92     13
2.80     12
0.56     12
1.95     12
0.27     12
1.42     12
0.87     12
5.00     12
0.25     11
0.99     11
1.08     11
0.98     11
0.72     10
0.71     10
1.28     10
2.55     10
1.78     10
1.12     10
0.86      9
2.85      9
0.22      9
2.05      9
0.97      9
4.00      9
3.45      9
1.68      9
1.72      9
0.20      9
0.96      8
3.20      8
2.75      8
0.54      8
4.25      8
1.18      8
1.54      8
6.50      8
6.00      8
1.76      8
1.26      8
0.48      8
1.99      7
0.79      7
0.46      7
1.29      7
2.90      7
0.39      7
3.70      7
1.27      7
1.36      7
3.30      7
1.19      7
1.02      7
0.37      7
0.41      6
0.29      6
1.01      6
0.64      6
0.43      6
0.24      6
3.35      6
4.10      6
0.66      6
0.53      6
1.49      6
3.90      6
1.98      6
3.65      6
5.50      6
1.07      6
1.51      6
2.95      6
3.05      6
1.16      6
0.89      6
0.49      6
0.21      6
1.59      6
1.14      6
1.39      6
1.34      6
1.13      6
0.94      6
1.47      5
0.74      5
1.83      5
0.93      5
4.50      5
1.79      5
2.29      5
1.93      5
2.12      5
3.75      5
0.69      5
6.75      5
1.33      5
0.62      5
2.78      5
1.24      5
1.17      5
2.22      5
0.67      5
1.82      5
1.43      5
1.91      5
1.69      5
1.44      5
1.92      5
0.33      5
0.68      5
1.62      5
3.95      4
6.15      4
0.91      4
1.71      4
1.48      4
5.60      4
5.90      4
1.64      4
3.60      4
1.77      4
1.52      4
1.73      4
5.25      4
1.31      4
1.58      4
2.09      4
1.22      4
4.30      4
4.85      4
7.00      4
3.10      4
1.66      4
0.31      4
0.73      4
0.47      4
1.23      4
0.58      4
4.75      3
0.83      3
0.34      3
3.85      3
2.33      3
2.79      3
1.41      3
3.49      3
1.67      3
4.80      3
2.51      3
2.01      3
2.08      3
1.09      3
2.28      3
3.80      3
2.03      3
1.04      3
2.24      3
0.52      3
3.15      3
1.21      3
2.36      3
1.57      3
1.88      3
0.84      3
0.51      3
5.80      3
1.63      3
4.20      3
0.23      2
2.91      2
0.59      2
3.29      2
5.70      2
1.56      2
2.26      2
2.99      2
2.87      2
2.57      2
5.20      2
4.60      2
3.21      2
3.32      2
1.87      2
3.55      2
4.70      2
4.45      2
2.04      2
4.55      2
7.50      2
11.00     2
2.58      2
2.14      2
0.81      2
6.20      2
2.23      2
4.49      2
2.52      2
2.13      2
2.17      2
8.50      2
8.00      2
1.46      2
4.26      2
2.41      2
2.02      2
14.00     2
6.25      1
3.87      1
3.67      1
8.25      1
2.37      1
4.67      1
3.39      1
3.63      1
2.34      1
3.79      1
5.49      1
6.30      1
11.25     1
7.15      1
2.82      1
4.95      1
5.31      1
3.19      1
4.40      1
4.63      1
2.98      1
4.78      1
6.16      1
5.30      1
2.72      1
2.21      1
2.48      1
3.83      1
3.46      1
5.40      1
2.63      1
1.11      1
6.44      1
7.56      1
4.79      1
2.97      1
4.94      1
10.75     1
9.14      1
8.35      1
1.06      1
2.11      1
6.10      1
5.75      1
10.00     1
0.17      1
2.77      1
2.61      1
2.62      1
4.86      1
5.15      1
9.30      1
1.74      1
4.21      1
4.16      1
4.52      1
1.84      1
8.44      1
13.20     1
2.92      1
2.38      1
2.64      1
2.49      1
0.63      1
2.06      1
2.07      1
0.44      1
2.32      1
1.86      1
9.95      1
9.20      1
0.16      1
2.86      1
3.72      1
0.57      1
0.19      1
7.52      1
2.96      1
1.53      1
0.61      1
15.00     1
7.80      1
1.97      1
4.02      1
3.98      1
2.69      1
2.54      1
3.23      1
7.90      1
6.02      1
2.44      1
9.00      1
3.99      1
7.40      1
3.78      1
Name: count, dtype: int64

In [121]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 5,000/sq.ft.      13
₹ 6,666/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 7,000/sq.ft.       8
₹ 12,000/sq.ft.      8
₹ 9,000/sq.ft.       7
₹ 11,111/sq.ft.      6
₹ 6,578/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,500/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 7,692/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 10,714/sq.ft.      5
₹ 5,556/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,142/sq.ft.       5
₹ 7,641/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 8,432/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 8,043/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 15,384/sq.ft.      4
₹ 8,484/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 8,163/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 8,139/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 8,474/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 7,317/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 8,148/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 5,397/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 9,904/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,921/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 7,541/sq.ft.       3
₹ 8,080/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 6,476/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 9,972/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 11,363/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 7,467/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 10,204/sq.ft.      3
₹ 4,513/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 6,722/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 13,333/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 7,796/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 5,424/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 11,724/sq.ft.      2
₹ 6,024/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 6,983/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 9,182/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 14,478/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 5,681/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 11,505/sq.ft.      2
₹ 8,410/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 7,610/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 5,896/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 6,313/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 7,751/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 9,074/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 10,526/sq.ft.      2
₹ 8,582/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 8,609/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 6,217/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 9,978/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 5,658/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 4,307/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 14,237/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 11,336/sq.ft.      2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 5,528/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 4,400/sq.ft.       2
₹ 5,470/sq.ft.       2
₹ 6,178/sq.ft.       2
₹ 5,204/sq.ft.       1
₹ 6,269/sq.ft.       1
₹ 7,860/sq.ft.       1
₹ 16,885/sq.ft.      1
₹ 9,767/sq.ft.       1
₹ 5,587/sq.ft.       1
₹ 6,940/sq.ft.       1
₹ 16,859/sq.ft.      1
₹ 14,084/sq.ft.      1
₹ 11,475/sq.ft.      1
₹ 9,156/sq.ft.       1
₹ 12,855/sq.ft.      1
₹ 7,910/sq.ft.       1
₹ 18,331/sq.ft.      1
₹ 24,300/sq.ft.      1
₹ 12,784/sq.ft.      1
₹ 26,936/sq.ft.      1
₹ 10,156/sq.ft.      1
₹ 7,194/sq.ft.       1
₹ 5,769/sq.ft.       1
₹ 8,866/sq.ft.       1
₹ 5,403/sq.ft.       1
₹ 6,378/sq.ft.       1
₹ 3,571/sq.ft.       1
₹ 7,581/sq.ft.       1
₹ 10,005/sq.ft.      1
₹ 7,410/sq.ft.       1
₹ 6,400/sq.ft.       1
₹ 4,715/sq.ft.       1
₹ 9,872/sq.ft.       1
₹ 6,594/sq.ft.       1
₹ 5,007/sq.ft.       1
₹ 6,376/sq.ft.       1
₹ 8,863/sq.ft.       1
₹ 4,320/sq.ft.       1
₹ 10,410/sq.ft.      1
₹ 5,178/sq.ft.       1
₹ 4,744/sq.ft.       1
₹ 9,406/sq.ft.       1
₹ 12,505/sq.ft.      1
₹ 11,153/sq.ft.      1
₹ 79/sq.ft.          1
₹ 3,768/sq.ft.       1
₹ 17,200/sq.ft.      1
₹ 6,615/sq.ft.       1
₹ 3,166/sq.ft.       1
₹ 9,838/sq.ft.       1
₹ 13,957/sq.ft.      1
₹ 8,768/sq.ft.       1
₹ 6,600/sq.ft.       1
₹ 11,738/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 12,800/sq.ft.      1
₹ 7,800/sq.ft.       1
₹ 15,590/sq.ft.      1
₹ 9,849/sq.ft.       1
₹ 11,482/sq.ft.      1
₹ 17,617/sq.ft.      1
₹ 6,106/sq.ft.       1
₹ 7,739/sq.ft.       1
₹ 16,030/sq.ft.      1
₹ 7/sq.ft.           1
₹ 9,955/sq.ft.       1
₹ 10,589/sq.ft.      1
₹ 6,443/sq.ft.       1
₹ 12,744/sq.ft.      1
₹ 9,285/sq.ft.       1
₹ 7,149/sq.ft.       1
₹ 13,115/sq.ft.      1
₹ 7,909/sq.ft.       1
₹ 12,920/sq.ft.      1
₹ 7,106/sq.ft.       1
₹ 5,883/sq.ft.       1
₹ 6,806/sq.ft.       1
₹ 9,502/sq.ft.       1
₹ 6,700/sq.ft.       1
₹ 5,750/sq.ft.       1
₹ 12,526/sq.ft.      1
₹ 12,244/sq.ft.      1
₹ 7,424/sq.ft.       1
₹ 10,361/sq.ft.      1
₹ 13,600/sq.ft.      1
₹ 5,308/sq.ft.       1
₹ 14,444/sq.ft.      1
₹ 7,188/sq.ft.       1
₹ 10,828/sq.ft.      1
₹ 15,664/sq.ft.      1
₹ 13,496/sq.ft.      1
₹ 9,463/sq.ft.       1
₹ 7,963/sq.ft.       1
₹ 12,185/sq.ft.      1
₹ 7,444/sq.ft.       1
₹ 6,345/sq.ft.       1
₹ 6,703/sq.ft.       1
₹ 6,150/sq.ft.       1
₹ 12,106/sq.ft.      1
₹ 13,074/sq.ft.      1
₹ 8,081/sq.ft.       1
₹ 13,136/sq.ft.      1
₹ 4,731/sq.ft.       1
₹ 5,142/sq.ft.       1
₹ 4,258/sq.ft.       1
₹ 17,441/sq.ft.      1
₹ 12,619/sq.ft.      1
₹ 4,546/sq.ft.       1
₹ 15,003/sq.ft.      1
₹ 3,970/sq.ft.       1
₹ 5,067/sq.ft.       1
₹ 14,118/sq.ft.      1
₹ 2,700/sq.ft.       1
₹ 18,492/sq.ft.      1
₹ 7,643/sq.ft.       1
₹ 16,923/sq.ft.      1
₹ 3,975/sq.ft.       1
₹ 4,705/sq.ft.       1
₹ 6,225/sq.ft.       1
₹ 17,990/sq.ft.      1
₹ 17,997/sq.ft.      1
₹ 18,477/sq.ft.      1
₹ 14,168/sq.ft.      1
₹ 7,036/sq.ft.       1
₹ 6,790/sq.ft.       1
₹ 5,420/sq.ft.       1
₹ 11,716/sq.ft.      1
₹ 12,181/sq.ft.      1
₹ 7,455/sq.ft.       1
₹ 7,032/sq.ft.       1
₹ 5,548/sq.ft.       1
₹ 5,888/sq.ft.       1
₹ 6,734/sq.ft.       1
₹ 9,024/sq.ft.       1
₹ 15,980/sq.ft.      1
₹ 28,000/sq.ft.      1
₹ 14,335/sq.ft.      1
₹ 15,793/sq.ft.      1
₹ 26,562/sq.ft.      1
₹ 6,300/sq.ft.       1
₹ 7,777/sq.ft.       1
₹ 14,100/sq.ft.      1
₹ 5,892/sq.ft.       1
₹ 10,158/sq.ft.      1
₹ 3,648/sq.ft.       1
₹ 7,772/sq.ft.       1
₹ 6,862/sq.ft.       1
₹ 13,969/sq.ft.      1
₹ 10,945/sq.ft.      1
₹ 13,269/sq.ft.      1
₹ 7,510/sq.ft.       1
₹ 8,514/sq.ft.       1
₹ 4,599/sq.ft.       1
₹ 14,110/sq.ft.      1
₹ 33,209/sq.ft.      1
₹ 14,202/sq.ft.      1
₹ 17,000/sq.ft.      1
₹ 15,240/sq.ft.      1
₹ 19,363/sq.ft.      1
₹ 5,832/sq.ft.       1
₹ 9,777/sq.ft.       1
₹ 8,160/sq.ft.       1
₹ 9,334/sq.ft.       1
₹ 5,897/sq.ft.       1
₹ 7,725/sq.ft.       1
₹ 10,895/sq.ft.      1
₹ 11,845/sq.ft.      1
₹ 23,401/sq.ft.      1
₹ 15,681/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 14,376/sq.ft.      1
₹ 9,221/sq.ft.       1
₹ 14,516/sq.ft.      1
₹ 19,200/sq.ft.      1
₹ 8,047/sq.ft.       1
₹ 4,888/sq.ft.       1
₹ 10,007/sq.ft.      1
₹ 13,765/sq.ft.      1
₹ 9,740/sq.ft.       1
₹ 9,552/sq.ft.       1
₹ 18,571/sq.ft.      1
₹ 14,500/sq.ft.      1
₹ 6,509/sq.ft.       1
₹ 11,426/sq.ft.      1
₹ 11,938/sq.ft.      1
₹ 12,318/sq.ft.      1
₹ 8,510/sq.ft.       1
₹ 12,810/sq.ft.      1
₹ 14,938/sq.ft.      1
₹ 6,709/sq.ft.       1
₹ 10,769/sq.ft.      1
₹ 8,087/sq.ft.       1
₹ 10,378/sq.ft.      1
₹ 13,696/sq.ft.      1
₹ 7,267/sq.ft.       1
₹ 11,832/sq.ft.      1
₹ 11,903/sq.ft.      1
₹ 4,881/sq.ft.       1
₹ 4,259/sq.ft.       1
₹ 11,185/sq.ft.      1
₹ 15,575/sq.ft.      1
₹ 7,804/sq.ft.       1
₹ 9,895/sq.ft.       1
₹ 17,455/sq.ft.      1
₹ 17,777/sq.ft.      1
₹ 12,312/sq.ft.      1
₹ 11,584/sq.ft.      1
₹ 5,011/sq.ft.       1
₹ 13,266/sq.ft.      1
₹ 7,600/sq.ft.       1
₹ 9,490/sq.ft.       1
₹ 9,558/sq.ft.       1
₹ 28,266/sq.ft.      1
₹ 7,869/sq.ft.       1
₹ 13,495/sq.ft.      1
₹ 18,400/sq.ft.      1
₹ 17,721/sq.ft.      1
₹ 5,530/sq.ft.       1
₹ 16,060/sq.ft.      1
₹ 12,346/sq.ft.      1
₹ 7,674/sq.ft.       1
₹ 14,871/sq.ft.      1
₹ 11,121/sq.ft.      1
₹ 16,486/sq.ft.      1
₹ 21,360/sq.ft.      1
₹ 26,790/sq.ft.      1
₹ 7,220/sq.ft.       1
₹ 12,627/sq.ft.      1
₹ 7,392/sq.ft.       1
₹ 12,818/sq.ft.      1
₹ 16,050/sq.ft.      1
₹ 18,500/sq.ft.      1
₹ 5,505/sq.ft.       1
₹ 13,125/sq.ft.      1
₹ 5,788/sq.ft.       1
₹ 13,690/sq.ft.      1
₹ 8,051/sq.ft.       1
₹ 28,101/sq.ft.      1
₹ 7,260/sq.ft.       1
₹ 14,950/sq.ft.      1
₹ 9,783/sq.ft.       1
₹ 12,544/sq.ft.      1
₹ 12,235/sq.ft.      1
₹ 14,079/sq.ft.      1
₹ 6,713/sq.ft.       1
₹ 13,790/sq.ft.      1
₹ 10,814/sq.ft.      1
₹ 12,140/sq.ft.      1
₹ 15,160/sq.ft.      1
₹ 6,661/sq.ft.       1
₹ 6,163/sq.ft.       1
₹ 10,901/sq.ft.      1
₹ 4,193/sq.ft.       1
₹ 3,309/sq.ft.       1
₹ 15,906/sq.ft.      1
₹ 11,294/sq.ft.      1
₹ 11,204/sq.ft.      1
₹ 11,470/sq.ft.      1
₹ 10,567/sq.ft.      1
₹ 12,788/sq.ft.      1
₹ 6,826/sq.ft.       1
₹ 9,528/sq.ft.       1
₹ 15,514/sq.ft.      1
₹ 14,563/sq.ft.      1
₹ 9,212/sq.ft.       1
₹ 6,888/sq.ft.       1
₹ 11,174/sq.ft.      1
₹ 10,841/sq.ft.      1
₹ 5,717/sq.ft.       1
₹ 5,867/sq.ft.       1
₹ 14,177/sq.ft.      1
₹ 10,174/sq.ft.      1
₹ 7,646/sq.ft.       1
₹ 6,961/sq.ft.       1
₹ 4,528/sq.ft.       1
₹ 8,580/sq.ft.       1
₹ 13,571/sq.ft.      1
₹ 11,686/sq.ft.      1
₹ 6,585/sq.ft.       1
₹ 7,230/sq.ft.       1
₹ 6,453/sq.ft.       1
₹ 5,973/sq.ft.       1
₹ 15,185/sq.ft.      1
₹ 12,152/sq.ft.      1
₹ 13,253/sq.ft.      1
₹ 12,190/sq.ft.      1
₹ 4,370/sq.ft.       1
₹ 4,355/sq.ft.       1
₹ 7,734/sq.ft.       1
₹ 5,418/sq.ft.       1
₹ 11,358/sq.ft.      1
₹ 12,599/sq.ft.      1
₹ 13,678/sq.ft.      1
₹ 5,004/sq.ft.       1
₹ 4,836/sq.ft.       1
₹ 10,595/sq.ft.      1
₹ 8,646/sq.ft.       1
₹ 10,461/sq.ft.      1
₹ 10,080/sq.ft.      1
₹ 8,172/sq.ft.       1
₹ 12,571/sq.ft.      1
₹ 11,914/sq.ft.      1
₹ 14,983/sq.ft.      1
₹ 8,759/sq.ft.       1
₹ 8,839/sq.ft.       1
₹ 16,750/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 10,334/sq.ft.      1
₹ 9,266/sq.ft.       1
₹ 11,860/sq.ft.      1
₹ 9,051/sq.ft.       1
₹ 9,622/sq.ft.       1
₹ 13,528/sq.ft.      1
₹ 4,864/sq.ft.       1
₹ 5,499/sq.ft.       1
₹ 7,065/sq.ft.       1
₹ 9,980/sq.ft.       1
₹ 9,036/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 13,878/sq.ft.      1
₹ 14,557/sq.ft.      1
₹ 12,325/sq.ft.      1
₹ 9,133/sq.ft.       1
₹ 6,819/sq.ft.       1
₹ 17,285/sq.ft.      1
₹ 13,929/sq.ft.      1
₹ 6,514/sq.ft.       1
₹ 6,580/sq.ft.       1
₹ 6,708/sq.ft.       1
₹ 13,846/sq.ft.      1
₹ 13,875/sq.ft.      1
₹ 12,400/sq.ft.      1
₹ 7,146/sq.ft.       1
₹ 14,074/sq.ft.      1
₹ 11,739/sq.ft.      1
₹ 12,110/sq.ft.      1
₹ 14,623/sq.ft.      1
₹ 6,523/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 7,437/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 3,935/sq.ft.       1
₹ 9,387/sq.ft.       1
₹ 9,117/sq.ft.       1
₹ 10,953/sq.ft.      1
₹ 11,052/sq.ft.      1
₹ 14,536/sq.ft.      1

In [122]:
df['price_per_sqft']=df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [123]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_numeric,price_crore
1221,2 BHK Flat in Sector 99A Gurgaon,conscient habitat,27.1 Lac,5599.0,Carpet area: 484 (44.97 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,Others,"Sector 99A Gurgaon, Gurgaon, Haryana",8th of 12 Floors,South-West,1 to 5 Year Old,NaN,Conscient habitat is one of gurgaon's most sou...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of...",2710000.0,0.27
1893,3 BHK Flat in Sector 102 Gurgaon,shapoorji pallonji joyville gurugram,1.8 Crore,10638.0,Super Built up area 1692(157.19 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"N/a, Sector 102 Gurgaon, Gurgaon, Haryana",1st of 26 Floors,East,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",Located in the popular residential address of ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction5 out of...",18000000.0,1.80
394,3 BHK Flat in Sector 86 Gurgaon,dlf the skycourt,1.56 Crore,8087.0,Super Built up area 1929(179.21 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3+ Balconies,Store Room,"H172, Sector 86 Gurgaon, Gurgaon, Haryana",17th of 19 Floors,South-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",This 3 bhk apartment is available for sale in ...,NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of...",15600000.0,1.56
1419,4 BHK Flat in Sector 81 Gurgaon,dlf the ultima,3.45 Crore,12356.0,Super Built up area 2792(259.39 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"236, Sector 81 Gurgaon, Gurgaon, Haryana",25th of 29 Floors,East,5 to 10 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...",Located in the popular residential address of ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4 out of...",34500000.0,3.45
1123,3 BHK Flat in Sector 90 Gurgaon,dlf new town heights,1.21 Crore,6243.0,Super Built up area 1930(179.3 sq.m.)Built Up ...,3 Bedrooms,3 Bathrooms,3+ Balconies,"Pooja Room,Servant Room","8888, Sector 90 Gurgaon, Gurgaon, Haryana",7th of 19 Floors,West,1 to 5 Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",This lovely 3 bhk apartment/flat in sector 90 ...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of...",12100000.0,1.21

In [124]:
df['areaWithType'].value_counts()

areaWithType
Super Built up area 1350(125.42 sq.m.)                                                                                          17
Super Built up area 1578(146.6 sq.m.)                                                                                           17
Super Built up area 1950(181.16 sq.m.)Carpet area: 1161 sq.ft. (107.86 sq.m.)                                                   17
Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)                                                    15
Super Built up area 2010(186.74 sq.m.)                                                                                          14
Super Built up area 2150(199.74 sq.m.)                                                                                          12
Carpet area: 1650 (153.29 sq.m.)                                                                                                11
Super Built up area 1950(181.16 sq.m.)                                                                                          11
Carpet area: 1150 (106.84 sq.m.)                                                                                                10
Super Built up area 1920(178.37 sq.m.)                                                                                          10
Super Built up area 1650(153.29 sq.m.)                                                                                          10
Super Built up area 1550(144 sq.m.)                                                                                             10
Super Built up area 1828(169.83 sq.m.)                                                                                           9
Super Built up area 1640(152.36 sq.m.)                                                                                           9
Carpet area: 1350 (125.42 sq.m.)                                                                                                 9
Carpet area: 1450 (134.71 sq.m.)                                                                                                 9
Carpet area: 489 (45.43 sq.m.)                                                                                                   9
Carpet area: 900 (83.61 sq.m.)                                                                                                   8
Carpet area: 750 (69.68 sq.m.)                                                                                                   8
Carpet area: 1950 (181.16 sq.m.)                                                                                                 8
Carpet area: 1800 (167.23 sq.m.)                                                                                                 8
Carpet area: 2400 (222.97 sq.m.)                                                                                                 8
Super Built up area 1760(163.51 sq.m.)Built Up area: 1186 sq.ft. (110.18 sq.m.)Carpet area: 1130 sq.ft. (104.98 sq.m.)           8
Super Built up area 1366(126.91 sq.m.)                                                                                           8
Super Built up area 2100(195.1 sq.m.)                                                                                            7
Carpet area: 1103 (102.47 sq.m.)                                                                                                 7
Carpet area: 1300 (120.77 sq.m.)                                                                                                 7
Super Built up area 2200(204.39 sq.m.)                                                                                           7
Carpet area: 2300 (213.68 sq.m.)                                                                                                 7
Super Built up area 2364(219.62 sq.m.)                                                                                           7
Super Built up area 2408(223.71 sq.m.)                                                                                           7
Carpet area: 1600 (148.64 sq.m.)                                                                                                 7
Carpet area: 1760 (163.51 sq.m.)                                                                                                 7
Super Built up area 3400(315.87 sq.m.)                                                                                           7
Super Built up area 1415(131.46 sq.m.)                                                                                           7
Super Built up area 2350(218.32 sq.m.)                                                                                           7
Super Built up area 1930(179.3 sq.m.)                                                                                            7
Super Built up area 1538(142.88 sq.m.)                                                                                           7
Super Built up area 1200(111.48 sq.m.)                                                                                           7
Carpet area: 700 (65.03 sq.m.)                                                                                                   6
Carpet area: 1423 (132.2 sq.m.)                                                                                                  6
Carpet area: 822 (76.37 sq.m.)                                                                                                   6
Super Built up area 2727(253.35 sq.m.)                                                                                           6
Carpet area: 1326 (123.19 sq.m.)                                                                                                 6
Super Built up area 1572(146.04 sq.m.)                                                                                           6
Super Built up area 1750(162.58 sq.m.)                                                                                           6
Super Built up area 2812(261.24 sq.m.)                                                                                           6
Super Built up area 2215(205.78 sq.m.)                                                                                           6
Super Built up area 2290(212.75 sq.m.)                                                                                           6
Super Built up area 3150(292.64 sq.m.)                                                                                           6
Super Built up area 1568(145.67 sq.m.)                                                                                           6
Carpet area: 1200 (111.48 sq.m.)                                                                                                 5
Super Built up area 1960(182.09 sq.m.)                                                                                           5
Carpet area: 450 (41.81 sq.m.)                                                                                                   5
Super Built up area 1875(174.19 sq.m.)                                                                                           5
Super Built up area 1000(92.9 sq.m.)                                                                                             5
Super Built up area 2000(185.81 sq.m.)                                                                                           5
Super Built up area 1850(171.87 sq.m.)                                                                                           5
Built Up area: 700 (65.03 sq.m.)                                                                                                 5
Carpet area: 850 (78.97 sq.m.)                                                                                                   5
Super Built up area 1565(145.39 sq.m.)                                                                                           5
Carpet area: 2000 (185.81 sq.m.)                                                                                                 5
Super Built up area 1975(183.48 sq.m.)                                                                                           5
Super Built up area 1997(185.53 sq.m.)                                                                                           5
Carpet area: 1975 (183.48 sq.m.)                                                                                                 5
Super Built up area 2025(188.13 sq.m.)                                                                                           5
Super Built up area 1700(157.94 sq.m.)                                                                                           5
Carpet area: 645 (59.92 sq.m.)                                                                                                   5
Carpet area: 1050 (97.55 sq.m.)                                                                                                  5
Super Built up area 1457(135.36 sq.m.)Carpet area: 849 sq.ft. (78.87 sq.m.)                                                      5
Super Built up area 1215(112.88 sq.m.)                                                                                           5
Super Built up area 1970(183.02 sq.m.)                                                                                           5
Super Built up area 2149(199.65 sq.m.)                                                                                           5
Super Built up area 1435(133.32 sq.m.)                                                                                           5
Super Built up area 1245(115.66 sq.m.)                                                                                           5
Super Built up area 1480(137.5 sq.m.)                                                                                            5
Super Built up area 2812(261.24 sq.m.)Built Up area: 2600 sq.ft. (241.55 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)           5
Carpet area: 600 (55.74 sq.m.)                                                                                                   5
Super Built up area 1360(126.35 sq.m.)                                                                                           5
Carpet area: 650 (60.39 sq.m.)                                                                                                   4
Carpet area: 2290 (212.75 sq.m.)                                                                                                 4
Super Built up area 1300(120.77 sq.m.)                                                                                           4
Super Built up area 1103(102.47 sq.m.)                                                                                           4
Carpet area: 1250 (116.13 sq.m.)                                                                                                 4
Super Built up area 1725(160.26 sq.m.)                                                                                           4
Super Built up area 1789(166.2 sq.m.)                                                                                            4
Super Built up area 1310(121.7 sq.m.)                                                                                            4
Built Up area: 2040 (189.52 sq.m.)                                                                                               4
Carpet area: 1225 (113.81 sq.m.)                                                                                                 4
Super Built up area 1365(126.81 sq.m.)                                                                                           4
Super Built up area 600(55.74 sq.m.)                                                                                             4
Carpet area: 1400 (130.06 sq.m.)                                                                                                 4
Super Built up area 1261(117.15 sq.m.)                                                                                           4
Carpet area: 800 (74.32 sq.m.)                                                                                                   4
Carpet area: 1340 (124.49 sq.m.)                                                                                                 4
Super Built up area 1780(165.37 sq.m.)                                                                                           4
Super Built up area 1100(102.19 sq.m.)                                                                                           4
Carpet area: 1549 (143.91 sq.m.)                                                                                                 4
Super Built up area 1900(176.52 sq.m.)                                                                                           4
Super Built up area 2802(260.31 sq.m.)Built Up area: 2225.56 sq.ft. (206.76 sq.m.)                                               4
Super Built up area 2095(194.63 sq.m.)                                                                                           4
Super Built up area 1790(166.3 sq.m.)                                                                                            4
Super Built up area 1900(176.52 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)                                                  4
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)           4
Super Built up area 1385(128.67 sq.m.)Built Up area: 940 sq.ft. (87.33 sq.m.)Carpet area: 845 sq.ft. (78.5 sq.m.)                4
Super Built up area 2545(236.44 sq.m.)                                                                                           4
Super Built up area 1942(180.42 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)Built Up area: 1600 sq.ft. (148.64 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)         4
Super Built up area 2191(203.55 sq.m.)                                                                                           4
Super Built up area 2358(219.07 sq.m.)                                                                                           4
Super Built up area 2950(274.06 sq.m.)                                                                                           4
Super Built up area 1430(132.85 sq.m.)                                                                                           4
Carpet area: 501 (46.54 sq.m.)                                                                                                   4
Super Built up area 1457(135.36 sq.m.)                                                                                           4
Super Built up area 2355(218.79 sq.m.)Built Up area: 1535 sq.ft. (142.61 sq.m.)Carpet area: 1403 sq.ft. (130.34 sq.m.)           4
Super Built up area 1930(179.3 sq.m.)Built Up area: 1929 sq.ft. (179.21 sq.m.)Carpet area: 1928 sq.ft. (179.12 sq.m.)            4
Super Built up area 2400(222.97 sq.m.)                                                                                           4
Carpet area: 1500 (139.35 sq.m.)                                                                                                 4
Super Built up area 1727(160.44 sq.m.)Carpet area: 1017 sq.ft. (94.48 sq.m.)                                                     4
Super Built up area 1825(169.55 sq.m.)                                                                                           4
Built Up area: 1103 (102.47 sq.m.)                                                                                               4
Super Built up area 650(60.39 sq.m.)                                                                                             4
Super Built up area 1081(100.43 sq.m.)                                                                                           4
Built Up area: 1350 (125.42 sq.m.)                                                                                               4
Carpet area: 481.73 (44.75 sq.m.)                                                                                                4
Carpet area: 1075 (99.87 sq.m.)                                                                                                  3
Carpet area: 531 (49.33 sq.m.)                                                                                                   3
Carpet area: 1210 (112.41 sq.m.)                                                                                                 3
Carpet area: 1385 (128.67 sq.m.)                                                                                                 3
Carpet area: 2100 (195.1 sq.m.)                                                                                                  3
Carpet area: 1120 (104.05 sq.m.)                                                                                                 3
Super Built up area 1370(127.28 sq.m.)                                                                                           3
Carpet area: 640 (59.46 sq.m.)                                                                                                   3
Carpet area: 1380 (128.21 sq.m.)                                                                                                 3
Super Built up area 1423(132.2 sq.m.)                                                                                            3
Carpet area: 591 (54.91 sq.m.)                                                                                                   3
Carpet area: 1630 (151.43 sq.m.)                                                                                                 3
Carpet area: 1180 (109.63 sq.m.)                                                                                                 3
Carpet area: 2298 (213.49 sq.m.)                                                                                                 3
Built Up area: 2400 (222.97 sq.m.)                                                                                               3
Carpet area: 710 (65.96 sq.m.)                                                                                                   3
Carpet area: 990 (91.97 sq.m.)                                                                                                   3
Super Built up area 1620(150.5 sq.m.)                                                                                            3
Super Built up area 1295(120.31 sq.m.)                                                                                           3
Built Up area: 1150 (106.84 sq.m.)                                                                                               3
Super Built up area 2905(269.88 sq.m.)                                                                                           3
Built Up area: 1310 (121.7 sq.m.)                                                                                                3
Super Built up area 1095(101.73 sq.m.)                                                                                           3
Built Up area: 1423 (132.2 sq.m.)                                                                                                3
Carpet area: 1750 (162.58 sq.m.)                                                                                                 3
Super Built up area 1630(151.43 sq.m.)                                                                                           3
Carpet area: 745 (69.21 sq.m.)                                                                                                   3

In [125]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1439
2 Bedrooms     948
4 Bedrooms     481
1 Bedroom      105
5 Bedrooms      32
6 Bedrooms       3
Name: count, dtype: int64

In [126]:
df[df['bedRoom'].isnull()].isnull().sum()

property_name      0
society            0
price              9
price_per_sqft     1
areaWithType       9
bedRoom            9
bathroom           9
balcony            9
additionalRoom     9
address            9
floorNum           9
facing             9
agePossession      9
nearbyLocations    9
description        9
furnishDetails     9
features           9
rating             9
price_numeric      0
price_crore        0
dtype: int64

In [127]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_numeric,price_crore
2849,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37
2850,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37
2851,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37
2852,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37
2922,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37
2923,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37
2924,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37
2926,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37
2927,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13700000.0,1.37

In [128]:
df=df[~df['bedRoom'].isnull()]

In [129]:
df['bedRoom']=df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [130]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_numeric,price_crore
869,1 BHK Flat in Palam Vihar,bestech park view residency,55.6 Lac,8553.0,Carpet area: 650 (60.39 sq.m.),1,1 Bathroom,2 Balconies,NaN,"Palam Vihar, Gurgaon, Haryana",7th of 8 Floors,South-West,5 to 10 Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...",This 1 bhk flat is located in bestech park vie...,"['1 Wardrobe', '2 Fan', '1 Geyser', '3 Light',...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Construction4 out of...",5560000.0,0.56
722,2 BHK Flat in Sector 107 Gurgaon,signature global solera,28 Lac,5725.0,Carpet area: 489 (45.43 sq.m.),2,2 Bathrooms,2 Balconies,NaN,"Sector 107 Gurgaon, Gurgaon, Haryana",6th of 14 Floors,West,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",Check out this 2 bhk apartment for sale in sig...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou...",2800000.0,0.28
2879,2 BHK Flat in Sector 95A Gurgaon,signature global rosellia,45 Lac,8754.0,Carpet area: 514 (47.75 sq.m.),2,2 Bathrooms,2 Balconies,NaN,"Sector 95A Gurgaon, Gurgaon, Haryana",14th of 14 Floors,NaN,0 to 1 Year Old,NaN,"East facing door, good ventilation balconies a...",NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Safety5 out of 5', 'Lifestyle4.5 out of 5', ...",4500000.0,0.45
421,4 BHK Flat in Sector 112 Gurgaon,experion windchants,5.49 Crore,11584.0,Super Built up area 4739(440.27 sq.m.)Built Up...,4,5 Bathrooms,3+ Balconies,Servant Room,"Wt-01/2/4/5/6, Sector 112 Gurgaon, Gurgaon, Ha...",5th of 25 Floors,South,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Available for sale luxury 4bhk servant apartme...,"['1 Exhaust Fan', '6 Geyser', '1 Stove', '7 AC...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction5 out of...",54900000.0,5.49
1184,3 BHK Flat in Sector 70A Gurgaon,aipl zen residences,1.82 Crore,10996.0,Super Built up area 1655(153.75 sq.m.)Built Up...,3,3 Bathrooms,3 Balconies,NaN,"Ddd, Sector 70A Gurgaon, Gurgaon, Haryana",12nd of 28 Floors,South,1 to 5 Year Old,"['Airia Mall', 'National Highway 8', 'Southern...",This 3 bhk flat is located in aipl zen residen...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",18200000.0,1.82

In [131]:
df[df['bathroom'].isnull()]

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating, price_numeric, price_crore]
Index: []

In [132]:
df['bathroom']=df['bathroom'].str.split(' ').str.get(0).astype('int')

In [133]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_numeric,price_crore
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",4500000.0,0.45
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",5000000.0,0.50
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",4000000.0,0.40
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,14700000.0,1.47
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",7000000.0,0.70

In [134]:
df['balcony'].value_counts()

balcony
3 Balconies     977
3+ Balconies    863
2 Balconies     751
1 Balcony       318
No Balcony       99
Name: count, dtype: int64

In [ ]:
df2 = pd.read_csv('your_file.csv')

In [135]:
df['balcony'].isnull().sum()

np.int64(0)

In [136]:
df['balcony']=df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [138]:
df[df['balcony']=='3+']

                                        property_name  \
8                    2 BHK Flat in Sector 88B Gurgaon
13                    2 BHK Flat in Sector 33 Gurgaon
21                    3 BHK Flat in Sector 79 Gurgaon
23                   3 BHK Flat in Sector 102 Gurgaon
24                   3 BHK Flat in Sector 113 Gurgaon
28                    3 BHK Flat in Sector 48 Gurgaon
32                    4 BHK Flat in Sector 43 Gurgaon
36                    2 BHK Flat in Sector 68 Gurgaon
41                                2 BHK Flat in Sohna
42                   3 BHK Flat in Sector 106 Gurgaon
43                    4 BHK Flat in Sector 82 Gurgaon
45                                3 BHK Flat in Sohna
46                    4 BHK Flat in Sector 90 Gurgaon
48                    3 BHK Flat in Sector 85 Gurgaon
49                   3 BHK Flat in Sector 82A Gurgaon
50                    3 BHK Flat in Sector 65 Gurgaon
55                4 BHK Flat in Sector 1A IMT Manesar
62                    4 BHK Flat in Sector 92 Gurgaon
64                   3 BHK Flat in Sector 37D Gurgaon
66                   3 BHK Flat in Sector 37C Gurgaon
78                    3 BHK Flat in Sector 49 Gurgaon
83                    5 BHK Flat in Sector 66 Gurgaon
86                    3 BHK Flat in Sector 61 Gurgaon
96                    4 BHK Flat in Sector 90 Gurgaon
105                   3 BHK Flat in Sector 77 Gurgaon
106                     3 BHK Flat in Sector-33 Sohna
116                     3 BHK Flat in Sector-33 Sohna
118                  4 BHK Flat in Sector 113 Gurgaon
119                  3 BHK Flat in Sector 103 Gurgaon
140                   3 BHK Flat in Sector 89 Gurgaon
147                               3 BHK Flat in Sohna
161                     3 BHK Flat in Sector-33 Sohna
165                   3 BHK Flat in Sector 77 Gurgaon
173                         4 BHK Flat in Palam Vihar
174                  3 BHK Flat in Sector 88A Gurgaon
175                   4 BHK Flat in Sector 91 Gurgaon
176                   4 BHK Flat in Sector 91 Gurgaon
180                  3 BHK Flat in Sector 37C Gurgaon
185                   4 BHK Flat in Sector 90 Gurgaon
191                   3 BHK Flat in Sector 79 Gurgaon
193                  4 BHK Flat in Sector 113 Gurgaon
197                   2 BHK Flat in Sector 65 Gurgaon
204                   3 BHK Flat in Sector 54 Gurgaon
216                               2 BHK Flat in Sohna
219                  5 BHK Flat in Sector 82A Gurgaon
229                   2 BHK Flat in Sector 79 Gurgaon
237                  3 BHK Flat in Sector 102 Gurgaon
244                   3 BHK Flat in Sector 71 Gurgaon
259                   4 BHK Flat in Sector 72 Gurgaon
265                   2 BHK Flat in Sector 79 Gurgaon
266                   2 BHK Flat in Sector 99 Gurgaon
269                   2 BHK Flat in Sector 79 Gurgaon
272                   3 BHK Flat in Sector 82 Gurgaon
274                  2 BHK Flat in Sector 37C Gurgaon
281                   3 BHK Flat in Sector 92 Gurgaon
288                   3 BHK Flat in Sector 65 Gurgaon
289                         3 BHK Flat in Palam Vihar
291                   4 BHK Flat in Sector 33 Gurgaon
292                              3 BHK Flat in Kanahi
307                   3 BHK Flat in Sector 61 Gurgaon
308                     3 BHK Flat in Nirvana Country
313                  4 BHK Flat in Sector 113 Gurgaon
314                  3 BHK Flat in Sector 102 Gurgaon
316                  4 BHK Flat in Sector 111 Gurgaon
318                   3 BHK Flat in Sector 48 Gurgaon
320                   3 BHK Flat in Sector 65 Gurgaon
321                         3 BHK Flat in Palam Vihar
334                     3 BHK Flat in Nirvana Country
337                  3 BHK Flat in Sector 102 Gurgaon
340                   3 BHK Flat in Sector 53 Gurgaon
342                  2 BHK Flat in Sector 70A Gurgaon
343                  3 BHK Flat in Sector 108 Gurgaon
345                   4 BHK Flat in Sector 48 Gurgaon
346                   3 BHK Flat in Sector 83 Gurgaon
355                     2 BHK Flat in Sector-33 Sohna
359                         3 BHK Flat in Palam Vihar
361                   3 BHK Flat in Sector 86 Gurgaon
366                   4 BHK Flat in Sector 22 Gurgaon
373                   3 BHK Flat in Sector 86 Gurgaon
375                  3 BHK Flat in Sector 113 Gurgaon
376                         4 BHK Flat in DLF Phase 3
381                         4 BHK Flat in Gwal Pahari
382                   4 BHK Flat in Sector 82 Gurgaon
383                    4 BHK Flat in Sector 1 Gurgaon
384                   4 BHK Flat in Sector 38 Gurgaon
385                         3 BHK Flat in DLF Phase 3
388                     3 BHK Flat in Nirvana Country
390                         3 BHK Flat in Palam Vihar
394                   3 BHK Flat in Sector 86 Gurgaon
403                   3 BHK Flat in Sector 67 Gurgaon
406                     4 BHK Flat in Ambience Island
408                  3 BHK Flat in Sector 103 Gurgaon
410               3 BHK Flat in Sector 1A IMT Manesar
411                   3 BHK Flat in Sector 81 Gurgaon
412                  4 BHK Flat in Sector 113 Gurgaon
413                  3 BHK Flat in Sector 37D Gurgaon
415                   4 BHK Flat in Sector 56 Gurgaon
420                  3 BHK Flat in Sector 112 Gurgaon
421                  4 BHK Flat in Sector 112 Gurgaon
422                   4 BHK Flat in Sector 84 Gurgaon
424                   3 BHK Flat in Sector 47 Gurgaon
425                   3 BHK Flat in Sector 56 Gurgaon
426                  5 BHK Flat in Sector 106 Gurgaon
429                   4 BHK Flat in Sector 48 Gurgaon
431                         3 BHK Flat in Palam Vihar
439                  3 BHK Flat in Sector 109 Gurgaon
443                   4 BHK Flat in Sector 91 Gurgaon
445                   4 BHK Flat in Sector 62 Gurgaon
448                   4 BHK Flat in Sector 54 Gurgaon
452                  3 BHK Flat in Sector 82A Gurgaon
453                  4 BHK Flat in Sector 82A Gurgaon
454                   4 BHK Flat in Sector 90 Gurgaon
455                  2 BHK Flat in Sector 106 Gurgaon
457                   3 BHK Flat in Sector 85 Gurgaon
460                   3 BHK Flat in Sector 72 Gurgaon
463                   3 BHK Flat in Sector 81 Gurgaon
464                   4 BHK Flat in Sector 69 Gurgaon
465                  3 BHK Flat in Sector 103 Gurgaon
466                  3 BHK Flat in Sector 109 Gurgaon
467                   4 BHK Flat in Sector 82 Gurgaon
468                   3 BHK Flat in Sector 60 Gurgaon
472                  4 BHK Flat in Sector 107 Gurgaon
473                   3 BHK Flat in Sector 22 Gurgaon
476                   3 BHK Flat in Sector 48 Gurgaon
478                  3 BHK Flat in Sector 102 Gurgaon
480                   3 BHK Flat in Sector 90 Gurgaon
485                   2 BHK Flat in Sector 74 Gurgaon
486                   2 BHK Flat in Sector 74 Gurgaon
487                   3 BHK Flat in Sector 74 Gurgaon
488                  3 BHK Flat in Sector 104 Gurgaon
492                   2 BHK Flat in Sector 85 Gurgaon
493                   3 BHK Flat in Sector 85 Gurgaon
496                   4 BHK Flat in Sector 47 Gurgaon
497                3 BHK Flat in Sector 1 Imt Manesar
498                3 BHK Flat in Sector 1 Imt Manesar
501                  4 BHK Flat in Sector 112 Gurgaon
507                   4 BHK Flat in Sector 72 Gurgaon
508                   3 BHK Flat in Sector 82 Gurgaon
509                   5 BHK Flat in Sector 51 Gurgaon
511                  3 BHK Flat in Sector 102 Gurgaon
514                   3 BHK Flat in Sector 56 Gurgaon
515                   3 BHK Flat in Sector 81 Gurgaon
516                   3 BHK Flat in Sector 81 Gurgaon
517                   3 BHK Flat in Sector 81 Gurgaon
519                   3 BHK Flat in Sector 81 Gurgaon
520                  3 BHK Flat in Sector 107 Gurgaon
521                  3 BHK Flat in Sector 104 Gurgaon
525                         3 BHK Flat in Palam Vihar
529               3 BHK Flat in Sector 1A IMT Manesar
530                  3 BHK Flat in Sector 103 Gurgaon
531                  2 BHK Flat in Sector 37C Gurgaon
534                   3 BHK Flat in Sector 83 Gurgaon
537                   4 BHK Flat in Sector 81 Gurgaon
538                   4 BHK Flat in Sector 90 Gurgaon
540                   4 BHK Flat in Sector 85 Gurgaon
542                   4 BHK Flat in Sector 85 Gurgaon
543                   2 BHK Flat in Sector 85 Gurgaon
546                   4 BHK Flat in Sector 72 Gurgaon
547                   4 BHK Flat in Sector 72 Gurgaon
548                   4 BHK Flat in Sector 72 Gurgaon
552                   3 BHK Flat in Sector 81 Gurgaon
553                   3 BHK Flat in Sector 81 Gurgaon
556                   4 BHK Flat in Sector 67 Gurgaon
559                   3 BHK Flat in Sector 65 Gurgaon
564                   4 BHK Flat in Sector 81 Gurgaon
565                   3 BHK Flat in Sector 81 Gurgaon
566                   3 BHK Flat in Sector 81 Gurgaon
567                   3 BHK Flat in Sector 81 Gurgaon
568                   3 BHK Flat in Sector 81 Gurgaon
569                   4 BHK Flat in Sector 92 Gurgaon
570                   4 BHK Flat in Sector 81 Gurgaon
571                             4 BHK Flat in Suncity
573                   3 BHK Flat in Sector 22 Gurgaon
579                   4 BHK Flat in Sector 77 Gurgaon
580                   3 BHK Flat in Sector 86 Gurgaon
581                  3 BHK Flat in Sector 113 Gurgaon
583                   3 BHK Flat in Sector 53 Gurgaon
584                   3 BHK Flat in Sector 54 Gurgaon
585                  3 BHK Flat in Sector 113 Gurgaon
586                4 BHK Flat in Sector 110 A Gurgaon
590                         4 BHK Flat in Gwal Pahari
593                   3 BHK Flat in Sector 67 Gurgaon
594                   4 BHK Flat in Sector 90 Gurgaon
595                   3 BHK Flat in Sector 90 Gurgaon
596                   4 BHK Flat in Sector 90 Gurgaon
597                   3 BHK Flat in Sector 90 Gurgaon
598                   4 BHK Flat in Sector 90 Gurgaon
599                   3 BHK Flat in Sector 90 Gurgaon
600                     3 BHK Flat in Nirvana Country
601                  3 BHK Flat in Sector 37D Gurgaon
603                   3 BHK Flat in Sector 65 Gurgaon
606                   3 BHK Flat in Sector 56 Gurgaon
607                   3 BHK Flat in Sector 56 Gurgaon
608                         3 BHK Flat in DLF Phase 3
611                   3 BHK Flat in Sector 81 Gurgaon
612                   3 BHK Flat in Sector 65 Gurgaon
614                   4 BHK Flat in Sector 90 Gurgaon
615                   4 BHK Flat in Sector 81 Gurgaon
616                   4 BHK Flat in Sector 67 Gurgaon
618                   4 BHK Flat in Sector 90 Gurgaon
621                  3 BHK Flat in Sector 82A Gurgaon
623                   3 BHK Flat in Sector 48 Gurgaon
624                  3 BHK Flat in Sector 102 Gurgaon
625                         2 BHK Flat in DLF Phase 4
631                  3 BHK Flat in Sector 109 Gurgaon
633                   3 BHK Flat in Sector 67 Gurgaon
634                   3 BHK Flat in Sector 61 Gurgaon
636                  2 BHK Flat in Sector 88A Gurgaon
639                   3 BHK Flat in Sector 77 Gurgaon
641               3 BHK Flat in Sector 1A IMT Manesar
642               3 BHK Flat in Sector 1A IMT Manesar
643                  3 BHK Flat in Sector 104 Gurgaon
645                  5 BHK Flat in Sector 110 Gurgaon
646                   3 BHK Flat in Sector 92 Gurgaon
647                   4 BHK Flat in Sector 67 Gurgaon
648                   4 BHK Flat in Sector 67 Gurgaon
649                   3 BHK Flat in Sector 67 Gurgaon
650                   3 BHK Flat in Sector 81 Gurgaon
651                   3 BHK Flat in Sector 81 Gurgaon
653                   4 BHK Flat in Sector 70 Gurgaon
655                   4 BHK Flat in Sector 22 Gurgaon
659                   3 BHK Flat in Sector 79 Gurgaon
663                   3 BHK Flat in Sector 70 Gurgaon
667                   3 BHK Flat in Sector 43 Gurgaon
668                   4 BHK Flat in Sector 67 Gurgaon
669                   3 BHK Flat in Sector 47 Gurgaon
673                         5 BHK Flat in Gwal Pahari
674                   4 BHK Flat in Sector 54 Gurgaon
676                   4 BHK Flat in Sector 90 Gurgaon
678                   4 BHK Flat in Sector 49 Gurgaon
680                   3 BHK Flat in Sector 81 Gurgaon
683                  3 BHK Flat in Sector 102 Gurgaon
684                   4 BHK Flat in Sector 85 Gurgaon
685                   4 BHK Flat in Sector 85 Gurgaon
689                   3 BHK Flat in Sector 95 Gurgaon
696                  3 BHK Flat in Sector 108 Gurgaon
697                   4 BHK Flat in Sector 62 Gurgaon
698                  3 BHK Flat in Sector 106 Gurgaon
700                  3 BHK Flat in Sector 113 Gurgaon
701                   3 BHK Flat in Sector 56 Gurgaon
708                  4 BHK Flat in Sector 111 Gurgaon
710                  3 BHK Flat in Sector 104 Gurgaon
711                  4 BHK Flat in Sector 104 Gurgaon
712                  4 BHK Flat in Sector 106 Gurgaon
713                  4 BHK Flat in Sector 102 Gurgaon
714                  4 BHK Flat in Sector 108 Gurgaon
718                  4 BHK Flat in Sector 104 Gurgaon
719                  2 BHK Flat in Sector 107 Gurgaon
725                  2 BHK Flat in Sector 107 Gurgaon
731                  4 BHK Flat in Sector 82A Gurgaon
733                  3 BHK Flat in Sector 103 Gurgaon
734                  2 BHK Flat in Sector 107 Gurgaon
735                  3 BHK Flat in Sector 107 Gurgaon
736                  3 BHK Flat in Sector 107 Gurgaon
739                  3 BHK Flat in Sector 103 Gurgaon
743                  3 BHK Flat in Sector 102 Gurgaon
746                   3 BHK Flat in Sector 69 Gurgaon
747                             3 BHK Flat in Manesar
748                    3 BHK Flat in Sector 1 Gurgaon
754                   3 BHK Flat in Sector 67 Gurgaon
755                   3 BHK Flat in Sector 67 Gurgaon
756                   3 BHK Flat in Sector 67 Gurgaon
758                   3 BHK Flat in Sector 67 Gurgaon
760                   3 BHK Flat in Sector 56 Gurgaon
761                   3 BHK Flat in Sector 43 Gurgaon
766                  3 BHK Flat in Sector 112 Gurgaon
768                   3 BHK Flat in Sector 48 Gurgaon
769                  4 BHK Flat in Sector 113 Gurgaon
771                   3 BHK Flat in Sector 81 Gurgaon
772                  4 BHK Flat in Sector 82A Gurgaon
777                   4 BHK Flat in Sector 53 Gurgaon
783                   3 BHK Flat in Sector 65 Gurgaon
785                  3 BHK Flat in Sector 37D Gurgaon
786                  4 BHK Flat in Sector 102 Gurgaon
787                  3 BHK Flat in Sector 102 Gurgaon
791                   4 BHK Flat in Sector 86 Gurgaon
792                   3 BHK Flat in Sector 86 Gurgaon
798                  4 BHK Flat in Sector 111 Gurgaon
801                               3 BHK Flat in Sohna
802                               2 BHK Flat in Sohna
810                  5 BHK Flat in Sector 113 Gurgaon
813                  3 BHK Flat in Sector 102 Gurgaon
818                  3 BHK Flat in Sector 107 Gurgaon
819                  4 BHK Flat in Sector 109 Gurgaon
821                  3 BHK Flat in Sector 109 Gurgaon
829                   4 BHK Flat in Sector 81 Gurgaon
830                   3 BHK Flat in Sector 81 Gurgaon
832                  3 BHK Flat in Sector 109 Gurgaon
833                  3 BHK Flat in Sector 109 Gurgaon
835                   3 BHK Flat in Sector 54 Gurgaon
837                   4 BHK Flat in Sector 56 Gurgaon
838                   3 BHK Flat in Sector 54 Gurgaon
841                   3 BHK Flat in Sector 81 Gurgaon
844                   5 BHK Flat in Sector 83 Gurgaon
852                   3 BHK Flat in Sector 86 Gurgaon
854                3 BHK Flat in Sector 1 Imt Manesar
855                   3 BHK Flat in Sector 54 Gurgaon
860                3 BHK Flat in Sector 110 A Gurgaon
861                   4 BHK Flat in Sector 67 Gurgaon
867                  4 BHK Flat in Sector 103 Gurgaon
872                   3 BHK Flat in Sector 63 Gurgaon
878                   3 BHK Flat in Sector 49 Gurgaon
879                   3 BHK Flat in Sector 54 Gurgaon
881                  4 BHK Flat in Sector 108 Gurgaon
886                   4 BHK Flat in Sector 56 Gurgaon
887                   3 BHK Flat in Sector 52 Gurgaon
888                  3 BHK Flat in Sector 109 Gurgaon
889                  4 BHK Flat in Sector 103 Gurgaon
892                  4 BHK Flat in Sector 104 Gurgaon
893                  3 BHK Flat in Sector 104 Gurgaon
894                  4 BHK Flat in Sector 104 Gurgaon
896                   3 BHK Flat in Sector 56 Gurgaon
897                  4 BHK Flat in Sector 104 Gurgaon
910                   3 BHK Flat in Sector 81 Gurgaon
912                  4 BHK Flat in Sector 82A Gurgaon
919                   4 BHK Flat in Sector 90 Gurgaon
922                   3 BHK Flat in Sector 81 Gurgaon
923                  3 BHK Flat in Sector 104 Gurgaon
925                  4 BHK Flat in Sector 106 Gurgaon
930                   3 BHK Flat in Sector 81 Gurgaon
933                  2 BHK Flat in Sector 107 Gurgaon
934                  4 BHK Flat in Sector 104 Gurgaon
936                  3 BHK Flat in Sector 107 Gurgaon
937                  3 BHK Flat in Sector 104 Gurgaon
938                  3 BHK Flat in Sector 107 Gurgaon
941                   3 BHK Flat in Sector 91 Gurgaon
946                   2 BHK Flat in Sector 74 Gurgaon
947                  3 BHK Flat in Sector 37C Gurgaon
951                   4 BHK Flat in Sector 62 Gurgaon
952                         3 BHK Flat in DLF Phase 5
955                  3 BHK Flat in Sector 109 Gurgaon
956                   3 BHK Flat in Sector 56 Gurgaon
960                  3 BHK Flat in Sector 102 Gurgaon
961                  4 BHK Flat in Sector 103 Gurgaon
963                  4 BHK Flat in Sector 106 Gurgaon
964                  3 BHK Flat in Sector 113 Gurgaon
965                  3 BHK Flat in Sector 113 Gurgaon
966                  3 BHK Flat in Sector 113 Gurgaon
968                  2 BHK Flat in Sector 106 Gurgaon
969                  2 BHK Flat in Sector 106 Gurgaon
970                  3 BHK Flat in Sector 106 Gurgaon
971                  4 BHK Flat in Sector 106 Gurgaon
972                  4 BHK Flat in Sector 106 Gurgaon
973                  3 BHK Flat in Sector 106 Gurgaon
974                  4 BHK Flat in Sector 99A Gurgaon
984                   4 BHK Flat in Sector 84 Gurgaon
995                   3 BHK Flat in Sector 83 Gurgaon
998                   3 BHK Flat in Sector 81 Gurgaon
999                   5 BHK Flat in Sector 49 Gurgaon
1001                  3 BHK Flat in Sector 91 Gurgaon
1002                 3 BHK Flat in Sector 88A Gurgaon
1003                 3 BHK Flat in Sector 88A Gurgaon
1015                 3 BHK Flat in Sector 109 Gurgaon
1017                 3 BHK Flat in Sector 112 Gurgaon
1018                  3 BHK Flat in Sector 79 Gurgaon
1019                  4 BHK Flat in Sector 72 Gurgaon
1021                  4 BHK Flat in Sector 85 Gurgaon
1022                  4 BHK Flat in Sector 72 Gurgaon
1023                  4 BHK Flat in Sector 72 Gurgaon
1024                  4 BHK Flat in Sector 72 Gurgaon
1025                 3 BHK Flat in Sector 113 Gurgaon
1026                  4 BHK Flat in Sector 48 Gurgaon
1030                  3 BHK Flat in Sector 22 Gurgaon
1033                 2 BHK Flat in Sector 37C Gurgaon
1035                 3 BHK Flat in Sector 37C Gurgaon
1037                    3 BHK Flat in Nirvana Country
1039                 4 BHK Flat in Sector 37D Gurgaon
1040                 4 BHK Flat in Sector 37D Gurgaon
1041                 3 BHK Flat in Sector 109 Gurgaon

In [137]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_numeric,price_crore
12,3 BHK Flat in Sector 79 Gurgaon,supertech araville,1.35 Crore,6940.0,Carpet area: 1945 (180.7 sq.m.),3,3,3,NaN,"Sector 79 Gurgaon, Gurgaon, Haryana",4th of 15 Floors,NaN,1 to 5 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Well spacious, nicely built with wooden floori...","['1 Water Purifier', '2 Fan', '1 Geyser', '3 L...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",13500000.0,1.35
2156,2 BHK Flat in Sohna,raheja maheshwara,48 Lac,4367.0,Super Built up area 1099(102.1 sq.m.),2,2,2,NaN,"Sohna, Gurgaon, Haryana",11st of 13 Floors,NaN,Jan 2024,"['NH 248A', 'Delhi Public School, Maruti Kunj'...",Residential apartment for sell.Located in sohn...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Lifestyle4 out of 5...",4800000.0,0.48
1993,2 BHK Flat in Sector 67 Gurgaon,shree vardhman mantra,56 Lac,7000.0,Carpet area: 800 (74.32 sq.m.),2,2,1,NaN,"Sector 67 Gurgaon, Gurgaon, Haryana",8th of 13 Floors,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Airia Mall', '...",Residential apartment for sell.The property co...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area4 out of 5', 'Construction4 out of...",5600000.0,0.56
1468,4 BHK Flat in Sector 110 Gurgaon,indiabulls enigma,3.6 Crore,10588.0,Super Built up area 3400(315.87 sq.m.),4,5,3,Servant Room,"Sector 110 Gurgaon, Gurgaon, Haryana",7th of 21 Floors,North,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",This 4 bhk flat is located in indiabulls enigm...,"['1 Modular Kitchen', '8 AC', 'No Bed', 'No Ch...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment4 out of 5', 'Lifestyle4 out of 5...",36000000.0,3.60
2967,3 BHK Flat in Sector 95 Gurgaon,sidhartha ncr greens,96 Lac,6201.0,Carpet area: 1548 (143.81 sq.m.),3,3,3,"Store Room,Pooja Room","Sector 95 Gurgaon, Gurgaon, Haryana",8th of 21 Floors,NaN,0 to 1 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Residential apartment for sell.Located on 8th ...,NaN,"['Lift(s)', 'Park', 'Piped-gas']","['Management4 out of 5', 'Green Area5 out of 5...",9600000.0,0.96

In [139]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     630
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room                25
Pooja Room,Study Room,Servant Room,Others         25
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Pooja Room,Study Room,Others                       2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Store Room,Pooja Room,Servant Room                 1
Study Room,Servant Room,Pooja Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Servant Room,Pooja Room,Store Room                 1
Store Room,Study Room                              1
Study Room,Store Room                              1
Servant Room,Pooja Room,Store Room,Study Room      1
Servant Room,Study Room,Pooja Room                 1
Servant Room,Pooja Room,Study Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [142]:
df['additionalRoom'].isnull().sum()

np.int64(1314)

In [146]:
df['additionalRoom'] = df['additionalRoom'].fillna('not available')

In [155]:
df['additionalRoom']=df['additionalRoom'].str.lower()

In [156]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_numeric,price_crore,aditionalRoom
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",4500000.0,0.45,not available
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",5000000.0,0.50,not available
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",4000000.0,0.40,not available
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,14700000.0,1.47,study room
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",7000000.0,0.70,study room

In [158]:
df['floorNum'].isnull().sum()

np.int64(2)

In [159]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           63
1st   of 4 Floors           61
14th   of 14 Floors         50
12nd   of 14 Floors         49
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
3rd   of 3 Floors           26
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 14 Floors          24
8th   of 19 Floors          24
5th   of 14 Floors          24
11st   of 14 Floors         23
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
Ground of 1 Floors          18
7th   of 18 Floors          18
6th   of 18 Floors          18
10th   of 19 Floors         18
12nd   of 12 Floors         17
10th   of 18 Floors         17
9th   of 13 Floors          17
7th   of 15 Floors          17
5th   of 15 Floors          16
3rd   of 18 Floors          16
1st   of 3 Floors           15
9th   of 15 Floors          15
2nd   of 12 Floors          15
6th   of 12 Floors          15
6th   of 19 Floors          14
6th   of 10 Floors          13
Ground of 4 Floors          13
7th   of 7 Floors           13
1st   of 2 Floors           13
5th   of 5 Floors           13
10th   of 26 Floors         13
3rd   of 13 Floors          13
10th   of 10 Floors         12
6th   of 15 Floors          12
4th   of 13 Floors          11
8th   of 12 Floors          11
8th   of 8 Floors           11
4th   of 10 Floors          11
6th   of 6 Floors           11
17th   of 17 Floors         11
9th   of 26 Floors          11
15th   of 19 Floors         11
11st   of 18 Floors         11
9th   of 24 Floors          11
16th   of 19 Floors         11
4th   of 15 Floors          10
4th   of 12 Floors          10
3rd   of 5 Floors           10
2nd   of 19 Floors          10
7th   of 26 Floors          10
3rd   of 9 Floors           10
10th   of 12 Floors         10
1st   of 26 Floors          10
12nd   of 18 Floors         10
7th   of 21 Floors          10
7th   of 13 Floors          10
6th   of 13 Floors          10
12nd   of 17 Floors          9
5th   of 18 Floors           9
9th   of 20 Floors           9
8th   of 22 Floors           9
18th   of 19 Floors          9
13rd   of 14 Floors          9
8th   of 15 Floors           9
3rd   of 15 Floors           9
3rd   of 12 Floors           9
14th   of 15 Floors          9
6th   of 16 Floors           9
6th   of 26 Floors           9
7th   of 12 Floors           9
7th   of 17 Floors           9
15th   of 29 Floors          9
14th   of 19 Floors          9
13rd   of 13 Floors          8
1st   of 19 Floors           8
9th   of 12 Floors           8
8th   of 13 Floors           8
2nd   of 5 Floors            8
14th   of 24 Floors          8
3rd   of 19 Floors           8
10th   of 17 Floors          8
2nd   of 15 Floors           8
8th   of 26 Floors           8
5th   of 9 Floors            8
2nd   of 8 Floors            8
4th   of 26 Floors           8
12nd   of 19 Floors          8
12nd   of 26 Floors          8
10th   of 13 Floors          8
12nd   of 24 Floors          8
8th   of 24 Floors           8
9th   of 18 Floors           8
5th   of 13 Floors           8
12nd   of 13 Floors          7
7th   of 19 Floors           7
5th   of 20 Floors           7
11st   of 11 Floors          7
11st   of 13 Floors          7
1st   of 13 Floors           7
2nd   of 17 Floors           7
16th   of 16 Floors          7
8th   of 10 Floors           7
Ground of 3 Floors           7
15th   of 15 Floors          7
11st   of 26 Floors          7
2nd   of 10 Floors           7
9th   of 19 Floors           7
8th   of 21 Floors           7
5th   of 29 Floors           7
10th   of 21 Floors          7
12nd   of 15 Floors          7
11st   of 24 Floors          7
2nd   of 13 Floors           7
4th   of 19 Floors           7
5th   of 25 Floors           6
14th   of 27 Floors          6
11st   of 12 Floors          6
16th   of 18 Floors          6
7th   of 20 Floors           6
10th   of 20 Floors          6
19th   of 19 Floors          6
4th   of 18 Floors           6
1st   of 10 Floors           6
12nd   of 22 Floors          6
17th   of 19 Floors          6
Ground of 16 Floors          6
10th   of 15 Floors          6
2nd   of 20 Floors           6
5th   of 22 Floors           6
10th   of 29 Floors          6
5th   of 10 Floors           6
6th   of 9 Floors            6
3rd   of 25 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
1st   of 5 Floors            6
11st   of 19 Floors          6
5th   of 8 Floors            5
3rd   of 20 Floors           5
10th   of 25 Floors          5
14th   of 17 Floors          5
9th   of 30 Floors           5
6th   of 20 Floors           5
11st   of 25 Floors          5
1st   of 15 Floors           5
1st   of 12 Floors           5
11st   of 30 Floors          5
1st   of 7 Floors            5
5th   of 19 Floors           5
9th   of 22 Floors           5
6th   of 17 Floors           5
4th   of 22 Floors           5
14th   of 29 Floors          5
7th   of 27 Floors           5
15th   of 28 Floors          5
17th   of 24 Floors          5
12nd   of 29 Floors          5
11st   of 16 Floors          5
11st   of 29 Floors          5
Ground of 21 Floors          5
10th   of 24 Floors          5
Ground of 12 Floors          5
15th   of 21 Floors          5
10th   of 27 Floors          5
15th   of 18 Floors          5
7th   of 8 Floors            5
8th   of 9 Floors            5
18th   of 29 Floors          5
8th   of 30 Floors           5
16th   of 26 Floors          5
12nd   of 21 Floors          5
6th   of 11 Floors           5
4th   of 9 Floors            5
Ground of 19 Floors          5
4th   of 27 Floors           5
14th   of 16 Floors          5
9th   of 11 Floors           5
25th   of 25 Floors          4
20th   of 20 Floors          4
18th   of 32 Floors          4
1st   of 18 Floors           4
3rd   of 11 Floors           4
23rd   of 26 Floors          4
4th   of 8 Floors            4
12nd   of 16 Floors          4
11st   of 15 Floors          4
2nd   of 16 Floors           4
9th   of 10 Floors           4
7th   of 9 Floors            4
22nd   of 24 Floors          4
19th   of 40 Floors          4
15th   of 32 Floors          4
14th   of 18 Floors          4
14th   of 21 Floors          4
7th   of 10 Floors           4
19th   of 24 Floors          4
11st   of 20 Floors          4
11st   of 17 Floors          4
17th   of 25 Floors          4
8th   of 16 Floors           4
20th   of 26 Floors          4
12nd   of 30 Floors          4
5th   of 16 Floors           4
22nd   of 30 Floors          4
2nd   of 9 Floors            4
15th   of 25 Floors          4
14th   of 26 Floors          4
17th   of 18 Floors          4
6th   of 30 Floors           4
Ground of 13 Floors          4
5th   of 24 Floors           4
15th   of 26 Floors          4
2nd   of 11 Floors           4
8th   of 20 Floors           4
15th   of 16 Floors          4
17th   of 26 Floors          4
13rd   of 25 Floors          4
7th   of 24 Floors           4
5th   of 23 Floors           4
Ground of 17 Floors          4
15th   of 23 Floors          4
7th   of 11 Floors           4
13rd   of 19 Floors          4
13rd   of 21 Floors          4
3rd   of 22 Floors           4
3rd   of 17 Floors           4
3rd   of 10 Floors           4
5th   of 17 Floors           3
21st   of 24 Floors          3
6th   of 24 Floors           3
1st   of 25 Floors           3
3rd   of 26 Floors           3
1st   of 11 Floors           3
15th   of 20 Floors          3
10th   of 16 Floors          3
1st   of 35 Floors           3
30th   of 32 Floors          3
8th   of 25 Floors           3
31st   of 32 Floors          3
18th   of 18 Floors          3
9th   of 16 Floors           3
26th   of 30 Floors          3
16th   of 20 Floors          3
3rd   of 8 Floors            3
7th   of 23 Floors           3
10th   of 30 Floors          3
5th   of 30 Floors           3
15th   of 40 Floors          3
8th   of 11 Floors           3
18th   of 30 Floors          3
5th   of 26 Floors           3
Ground of 18 Floors          3
9th   of 21 Floors           3
19th   of 29 Floors          3
6th   of 8 Floors            3
15th   of 39 Floors          3
8th   of 40 Floors           3
2nd   of 26 Floors           3
12nd   of 23 Floors          3
10th   of 28 Floors          3
3rd   of 16 Floors           3
4th   of 20 Floors           3
17th   of 30 Floors          3
17th   of 29 Floors          3
19th   of 30 Floors          3
6th   of 29 Floors           3
17th   of 20 Floors          3
11st   of 27 Floors          3
27th   of 27 Floors          3
4th   of 21 Floors           3
14th   of 32 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
24th   of 24 Floors          3
21st   of 22 Floors          3
4th   of 16 Floors           3
4th   of 29 Floors           3
19th   of 21 Floors          3
6th   of 21 Floors           3
8th   of 17 Floors           3
20th   of 28 Floors          3
Ground of 26 Floors          3
12nd   of 27 Floors          3
6th   of 22 Floors           3
6th   of 23 Floors           3
9th   of 40 Floors           3
18th   of 26 Floors          3
15th   of 22 Floors          3
13rd   of 15 Floors          3
23rd   of 23 Floors          3
9th   of 29 Floors           2
43   of 47 Floors            2
2nd   of 25 Floors           2
20th   of 22 Floors          2
11st   of 21 Floors          2
4th   of 34 Floors           2
Lower Ground of 4 Floors     2
10th   of 22 Floors          2
8th   of 34 Floors           2
1st   of 22 Floors           2
8th   of 32 Floors           2
39th   of 40 Floors          2
14th   of 20 Floors          2
20th   of 23 Floors          2
9th   of 17 Floors           2
2nd   of 24 Floors           2
16th   of 24 Floors          2
19th   of 20 Floors          2
Ground of 23 Floors          2
4th   of 11 Floors           2
18th   of 21 Floors          2
14th   of 28 Floors          2
16th   of 27 Floors          2
16th   of 32 Floors          2
8th   of 29 Floors           2
3rd   of 32 Floors           2
7th   of 29 Floors           2
16th   of 21 Floors          2
25th   of 30 Floors          2
9th   of 28 Floors           2
13rd   of 40 Floors          2
6th   of 31 Floors           2
1st   of 24 Floors           2
12nd   of 25 Floors          2
4th   of 5 Floors            2
7th   of 16 Floors           2
28th   of 30 Floors          2
Ground of 51 Floors          2
10th   of 32 Floors          2
7th   of 36 Floors           2
3rd   of 29 Floors           2
3rd   of 27 Floors           2
10th   of 11 Floors          2
2nd   of 21 Floors           2
8th   of 28 Floors           2
15th   of 17 Floors          2
20th   of 25 Floors          2
7th   of 22 Floors           2
2nd   of 40 Floors           2
9th   of 27 Floors           2
21st   of 27 Floors          2
2nd   of 32 Floors           2
18th   of 24 Floors          2
23rd   of 34 Floors          2
1st   of 8 Floors            2
1st   of 20 Floors           2
1st   of 30 Floors           2
22nd   of 25 Floors          2
2nd   of 7 Floors            2
2nd   of 18 Floors           2
3rd   of 24 Floors           2
16th   of 34 Floors          2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
16th   of 30 Floors          2
23rd   of 29 Floors          2
25th   of 29 Floors          2
11st   of 23 Floors          2
8th   of 23 Floors           2
19th   of 27 Floors          2
10th   of 40 Floors          2
13rd   of 30 Floors          2
7th   of 30 Floors           2
13rd   of 20 Floors          2
27th   of 29 Floors          2
15th   of 31 Floors          2
2nd   of 28 Floors           2
2nd   of 6 Floors            2
24th   of 30 Floors          2
16th   of 36 Floors          2
5th   of 11 Floors           2
1st   of 16 Floors           2
1st   of 17 Floors           2
3rd   of 33 Floors           2
17th   of 33 Floors          2
15th   of 45 Floors          2
40th   of 40 Floors          2
31st   of 40 Floors          1
11st   of 22 Floors          1
Ground of 11 Floors          1
29th   of 31 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
20th   of 34 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
33rd   of 48 Floors          1
35th   of 35 Floors          1
26th   of 47 Floors          1
Ground of 24 Floors          1
7th   of 25 Floors           1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
1st   of 44 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
25th   of 36 Floors          1
21st   of 28 Floors          1
7th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
3rd   of 6 Floors            1
20th   of 40 Floors          1
9th   of 42 Floors           1
8th   of 31 Floors           1
20th   of 30 Floors          1
18th   of 51 Floors          1
24th   of 27 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
12nd   of 39 Floors          1
38th   of 40 Floors          1
18th   of 40 Floors          1
35th   of 51 Floors          1
22nd   of 28 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
15th   of 27 Floors          1
3rd   of 40 Floors           1
6th   of 25 Floors           1
16th   of 25 Floors          1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
10th   of 39 Floors          1
21st   of 26 Floors          1
22nd   of 40 Floors          1
16th   of 41 Floors          1
7th   of 40 Floors           1
12nd   of 40 Floors          1
3rd   of 28 Floors           1
17th   of 28 Floors          1
3rd   of 30 Floors           1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
12nd   of 34 Floors          1
5th   of 34 Floors           1
9th   of 25 Floors           1
45   of 47 Floors            1
Ground of 25 Floors          1
9th   of 23 Floors           1
33rd   of 33 Floors          1
1st   of 6 Floors            1
20th   of 24 Floors          1
13rd   of 17 Floors          1
Ground of 6 Floors           1
Basement of 13 Floors        1
18th   of 22 Floors          1
17th   of 22 Floors          1
24th   of 36 Floors          1
3rd   of 36 Floors           1
5th   of 6 Floors            1
8th   of 35 Floors           1
Lower Ground of 1 Floors     1
5th   of 35 Floors           1
Ground of 2 Floors           1
10th   of 33 Floors          1
18th   of 35 Floors          1
17th   of 31 Floors          1
21st   of 23 Floors          1
Ground of 5 Floors           1
Ground of 40 Floors          1
13rd   of 22 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
23rd   of 24 Floors          1
17th   of 47 Floors          1
4th   of 6 Floors            1
30th   of 34 Floors          1
13rd   of 47 Floors          1
34th   of 42 Floors          1
29th   of 39 Floors          1
18th   of 20 Floors          1
3rd   of 31 Floors           1
27th   of 30 Floors          1
34th   of 34 Floors          1
5th   of 36 Floors           1
19th   of 32 Floors          1
16th   of 45 Floors          1
22nd   of 23 Floors          1
7th   of 28 Floors           1
21st   of 36 Floors          1
14th   of 41 Floors          1
Ground of 29 Floors          1
22nd   of 26 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [161]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_numeric,price_crore,aditionalRoom
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08 Crore,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN,10800000.0,1.08,not available
2766,2 BHK Flat in Sector 78 Gurgaon,nan,60 Lac,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",6000000.0,0.60,not available

In [163]:
df['floorNum']=df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [164]:
df['facing'].value_counts()

facing
North-East    506
East          492
North         302
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [165]:
df['facing'].isnull().sum()

np.int64(881)

In [166]:
df['facing']=df['facing'].fillna('NA')

In [167]:
df['facing'].isnull().sum()

np.int64(0)

In [169]:
df.insert(loc=4,column='area',value=round((df['price_crore']*10000000)/df['price_per_sqft']))

In [184]:
df.insert(loc=1,column='property_type',value='flat')

ValueError: cannot insert property_type, already exists

In [185]:
df.head(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [186]:
df.drop(columns=['price', 'price_numeric', 'aditionalRoom'], inplace=True)

KeyError: "['price_numeric', 'aditionalRoom'] not found in axis"

In [187]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [188]:
df.rename(columns={'price_crore':'price'},inplace=True)
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2030,3 BHK Flat in Sector 113 Gurgaon,flat,smartworld one dxp,2.00,11074.0,1806.0,Built Up area: 1806 (167.78 sq.m.)Carpet area:...,3,3,3,not available,"Sector 113, Sector 113 Gurgaon , Gurgaon, Haryana",12,North,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Best in class property available at sector 113...,NaN,NaN,NaN
980,3 BHK Flat in Sector 83 Gurgaon,flat,vatika lifestyle homes,1.05,5982.0,1755.0,Super Built up area 1755(163.04 sq.m.),3,3,2,"pooja room,store room,study room,servant room","Tower 1, Sector 83 Gurgaon, Gurgaon, Haryana",14,South-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH – 08', 'Knowledge Tre...","Combination of low-Rise, mid-Rise, and high-Ri...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4 out ..."
2516,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,0.95,10383.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 6...,2,2,2,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",14,NA,undefined,NaN,Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4.5 out of..."
679,3 BHK Flat in Sector 86 Gurgaon,flat,dlf the skycourt,1.59,8242.0,1929.0,Super Built up area 1929(179.21 sq.m.)Built Up...,3,3,3,others,"171, Sector 86 Gurgaon, Gurgaon, Haryana",17,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",Dlf the skycourt is one of the most popular de...,"['5 Fan', '1 Exhaust Fan', '5 Light', '5 AC', ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1769,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.60,10139.0,1578.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"Sector 69 Gurgaon, Gurgaon, Haryana",0,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",3 bhk flat on ground floor. Located in the pop...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."

In [181]:
col = df.pop('price')

df.insert(3, 'price', col)

In [189]:
df.info()

<class 'pandas.DataFrame'>
Index: 3008 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3008 non-null   str
 1   property_type    3008 non-null   str
 2   society          3008 non-null   str
 3   price            3008 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     3008 non-null   str
 7   bedRoom          3008 non-null   int64
 8   bathroom         3008 non-null   int64
 9   balcony          3008 non-null   object
 10  additionalRoom   3008 non-null   str
 11  address          3002 non-null   str
 12  floorNum         3006 non-null   object
 13  facing           3008 non-null   str
 14  agePossession    3007 non-null   str
 15  nearbyLocations  2913 non-null   str
 16  description      3008 non-null   str
 17  furnishDetails   2203 non-null   str
 18  features         2594 non-null   str
 19  rating           2676 non-null   str
dtypes: float64(3), int64(2), object(2), str(13)
memory usage: 493.5+ KB

In [191]:
df.shape

(3008, 20)

In [192]:
df.to_csv('flats_cleaned.csv',index=False)