In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('properties.csv')

In [4]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3703,4 BHK Flat in Mehrauli Gurgaon Road,flat,unitech heritage city,4.26,13108.0,3250.0,Built Up area: 3250 (301.93 sq.m.),4,4,0,not available,"Mehrauli Gurgaon Road, Mehrauli Gurgaon Road, ...",9.0,NaN,undefined,"['Mg road metro station', 'Iffco chowk metro s...",Best in class property available at mehrauli g...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2789,2 BHK Flat in Sector 84 Gurgaon,flat,pivotal devaan,0.37,6346.0,583.0,Super Built up area 583(54.16 sq.m.)Carpet are...,2,2,1,not available,"Sector 84 Gurgaon, Gurgaon, Haryana",5.0,North-West,1 to 5 Year Old,"['Dwarka Expressway', 'RPS International Schoo...","Its 2bhk, semi furnished flat, middle floor, p...",[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3964,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,0.97,10601.0,915.0,Super Built up area 915(85.01 sq.m.)Carpet are...,2,2,2,not available,"Sector 102 Gurgaon, Gurgaon, Haryana",12.0,NaN,Within 6 months,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...","Ast facingsituated in sector 102 gurgaon, shap...","['1 Water Purifier', '1 Fan', '1 Geyser', '1 L...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Amenities5 out of 5'..."
1886,7 Bedroom House for sale in DLF Phase 1,house,independent,18.25,18250.0,10000.0,Plot area 550(51.1 sq.m.)Carpet area: 10000 sq...,7,9,3+,"pooja room,study room,servant room,store room","A Block, DLF Phase 1, Gurgaon, Haryana",4.0,East,1 to 5 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",Ultra luxury duplex kothi sale in dlf phase 1 ...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
2629,19 Bedroom House for sale in Sector 17A Gurgaon,house,independent,3.93,24214.0,1623.0,Plot area 1623(150.78 sq.m.)Built Up area: 162...,19,17,3,"study room,servant room,store room,pooja room","690, Sector 17A Gurgaon, Gurgaon, Haryana",4.0,North-West,1 to 5 Year Old,"['Iffco chowk metro station', 'Citi bank ATM',...","8% return yearly, very safe sector, supportive...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [5]:
df.shape

(3982, 20)

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3982 entries, 0 to 3981
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3982 non-null   str
 1   property_type    3982 non-null   str
 2   society          3981 non-null   str
 3   price            3982 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3982 non-null   str
 7   bedRoom          3982 non-null   int64
 8   bathroom         3982 non-null   int64
 9   balcony          3982 non-null   str
 10  additionalRoom   3586 non-null   str
 11  address          3971 non-null   str
 12  floorNum         3961 non-null   float64
 13  facing           2789 non-null   str
 14  agePossession    3981 non-null   str
 15  nearbyLocations  3764 non-null   str
 16  description      3982 non-null   str
 17  furnishDetails   2935 non-null   str
 18  features         3256 non-null   str
 19  rating           3528 non-null   str
dtypes: float64(4), int64(2), str(14)
memory usage: 622.3 KB

In [8]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                 0
price_per_sqft       41
area                 41
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom      396
address              11
floorNum             21
facing             1193
agePossession         1
nearbyLocations     218
description           0
furnishDetails     1047
features            726
rating              454
dtype: int64

In [9]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [10]:
df['sector'] = df['sector'].str.lower()

In [11]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     81
sector 83                                                     69
sector 37d                                                    69
sector 104                                                    67
sector 86                                                     67
sector 107                                                    60
sector 108                                                    59
sector 95                                                     58
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
nirvana country                                               53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
sector 113                                                    43
dlf phase 1                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
laxman vihar                                                  29
sector 77                                                     29
sector 71                                                     27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
dlf phase 3                                                   22
sector 67a                                                    22
sector 111                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 110                                                    16
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
gwal pahari                                                   15
rajendra park                                                 15
sector 3                                                      14
sector 53                                                     14
sector 1 imt manesar                                          14
dlf phase 5                                                   14
sector 52                                                     14
sector 76                                                     14
sector 36a                                                    13
sector 31                                                     13
laxman vihar phase 2                                          13
sector 50                                                     13
sector 46                                                     13
sohna road                                                    12
sector 93                                                     12
sector 38                                                     12
uppals southend                                               12
sector 39                                                     12
sector 47                                                     11
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 95a                                                    11
sector 1a imt manesar                                         10
sector 7                                                      10
ashok vihar phase 2                                            9
sector 4                                                       9
south city 1                                                   9
sector 55                                                      9
dwarka expressway                                              8
sector 59                                                      8
mehrauli  road                                                 8
malibu town                                                    8
sector 89 a                                                    8
sector 43                                                      8
sector 40                                                      8
sector 10a                                                     8
palam vihar extension                                          8
c block sushant lok phase 1                                    8
sector 57                                                      8
sector 1                                                       7
new colony                                                     7
sector 26                                                      7
surat nagar 1                                                  7
sector 51                                                      7
mianwali colony                                                7
sector 36 sohna                                                7
sector 11                                                      7
sector 58                                                      7
sector 5                                                       6
ashok vihar                                                    6
ansal plaza                                                    6
jacobpura                                                      6
jyoti park                                                     6
rajiv nagar                                                    6
sector 23a                                                     5
sector 2                                                       5
sector 105                                                     5
chakkarpur                                                     5
dharam colony                                                  5
sector 28                                                      5
sushant lok phase 2                                            5
sector 9                                                       5
saraswati vihar                                                5
dayanand colony                                                5
manesar                                                        5
sector 80                                                      5
subhash nagar                                                  5
sector 30                                                      5
madanpuri                                                      5
arjun nagar                                                    5
new palam vihar                                                5
greenwood city                                                 5
vishnu garden                                                  4
sector 36                                                      4
bhim nagar                                                     4
adarsh nagar                                                   4
imt manesar                                                    4
shivpuri                                                       4
shivaji nagar                                                  4
sector 6                                                       4
garhi harsaru                                                  4
sector 45                                                      4
krishna colony                                                 4
valley view estate                                             4
surya vihar                                                    4
sector 12a                                                     4
new                                                            4
sector 8                                                       4
sector 17                                                      4
devilal colony                                                 4
sector 12                                                      4
bhondsi                                                        4
baldev nagar                                                   4
sector 3a                                                      4
suncity                                                        4
ravi nagar                                                     4
mg road                                                        3
sheetla colony                                                 3
sector 23                                                      3
prem nagar                                                     3
gandhi nagar                                                   3
laxmi garden                                                   3
sector 73                                                      3
sector 15                                                      3
sector 27                                                      3
sector 17b                                                     3
maruti kunj                                                    3
sector 88b                                                     3
sector 110 a                                                   3
patel nagar                                                    3
a block sushant lok phase 1                                    3
shakti nagar                                                   3
b block sushant lok phase 1                                    3
sector 17a                                                     3
sector-2 sohna                                                 3
surat nagar                                                    3
golf course road                                               2
mayfield garden                                                2
rosewood                                                       2
sector 41                                                      2
manohar nagar                                                  2
lajpat nagar                                                   2
hira nagar                                                     2
ambience island                                                2
rajiv chowk                                                    2
, delhi ncr                                                    2
samaspur                                                       2
golf course ext road                                           2
block a surya vihar                                            2
sector 24                                                      2
sushant lok                                                    2
sector 15 part 2                                               2
shankar vihar                                                  2
new basti                                                      2
bissar                                                         2
pratap nagar                                                   2
new palam vihar phase 2                                        2
daulatabad                                                     2
sispal vihar                                                   2
faridabad road                                                 2
nars                                                           2
west rajiv nagar                                               2
sector-11 sohna                                                2
sector 21                                                      2
bhawani enclave                                                2
sector 32                                                      2
acharya puri                                                   2
mohan nagar                                                    2
shanti nagar                                                   2
sohna  road                                                    2
surat nagar phase 2                                            2
new palam vihar phase 1                                        2
farukhnagar                                                    2
iffco chowk                                                    2
sector 15 part 1                                               2
anand garden, sector-105                                       1
tekchand nagar                                                 1
vir nagar                                                      1
bptp                                                           1
sector-5 sheetla colony                                        1
jat colony,fazilpur/taj nagar road                             1
sector 37b                                                     1
pataudi road                                                   1
mahalaxmi garden, rajendra place                               1
rattan garden                                                  1
om nagar                                                       1
laxmna vihar, phase 2                                          1
saroop garden rajendra park                                    1
sector 37a                                                     1
sector-35 sohna                                                1
carterpuri village                                             1
block g sector-57                                              1
sector 9b                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
saraswati enclave                                              1
hsiidc plot sector 1 imt manesar                               1
kheri                                                          1
shivji park colony                                             1
garauli kalan                                                  1
ansal's palam vihar                                            1
new colony, sector 7                                           1
godrej aria , sector 79 ,                                      1
laxman vihar, railway road,                                    1
park view                                                      1
near khandsa road                                              1
sector 21a faridabad                                           1
sai kunj                                                       1
khandsa                                                        1
part 3 sector 5                                                1
sector 42                                                      1
b1 block sector 57                                             1
ravi nager basai road                                          1
bhimgarh kheri phase 3                                         1
old delhi road, opp sector-14                                  1
sector-7 hous                                                  1
ats marigold                                                   1
urban estate, sector 5                                         1
g block dlf city phase 1                                       1
begampur khatola                                               1
sector 13                                                      1
ashok vihar phase 3                                            1
near nand hospital                                             1
lucknow                                                        1
alipur                                                         1
jacobpura near sadar bazar                                     1
naharpur rupa                                                  1
rajiv colony                                                   1
kanahi                                                         1
near euro                                                      1
udyog vihar phase 1                                            1
new jyoti park                                                 1
sultanpur                                                      1
sadar bazar                                                    1
civil l                                                        1
near pataudi chowk                                             1
block h ashok vihar phase iii extension                        1
bhora kalan                                                    1
hno 13 sagar enclave sura                                      1
south city                                                     1
ram nagar                                                      1
damdma                                                         1
sector 4 urban estate                                          1
devi lal colony gali no 12 gurgaon nr omkar public school      1
ashok vihar phase i                                            1
nirvana country pocket h                                       1
dhankot                                                        1
sector 17c                                                     1
v block dlf phase 3                                            1
dharam colony block e                                          1
sector 5 chowk                                                 1
huda saraswati vihar                                           1
near sector 1 market                                           1
sector-5 sohna                                                 1
mahavir pura                                                   1
heritage city                                                  1
gopal nagar, garhi ghasita, sonipat                            1
cyber city                                                     1
Name: count, dtype: int64

In [12]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [13]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [14]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [15]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [16]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [17]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [18]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [19]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [20]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      81
sector 104                     74
sector 83                      69
sector 37d                     69
sector 86                      67
sector 50                      66
sector 107                     60
sector 108                     59
sector 95                      58
sector 56                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 43                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 82                      42
sector 61                      42
sector 7                       40
sector 4                       38
sector 106                     38
sector 99a                     32
sector 54                      31
sector 12                      31
sector 68                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 105                     24
sector 57                      24
sector 112                     24
sector 24                      24
sector 14                      23
sector 88a                     23
sector 33                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 82a                     20
sector 22                      20
sector 47                      19
gwal pahari                    19
sector 78                      19
sector 74                      18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 99                      16
sector 110                     16
sector 63                      15
sector 60                      15
sector 53                      14
sector 1 manesar               14
sector 52                      14
sector 76                      14
sector 55                      14
sector 36a                     13
sector 31                      13
sector 4 phase 2               13
sector 6                       13
sector 46                      13
sector 9                       13
sohna road road                12
sector 93                      12
sector 38                      12
sector 39                      12
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 95a                     11
sector 1a manesar              10
sector 13                      10
manesar                         9
sector 23                       9
sector 45                       9
sector 3 phase 2                9
sector 8                        9
dwarka expressway               8
sector 59                       8
sector 89 a                     8
sector 17                       8
sector 40                       8
sector 10a                      8
sector 2 extension              8
c block sector 43               8
sector 1                        7
sector 51                       7
sector 36 sohna road            7
sector 58                       7
sector 5                        6
sector 21                       6
sector 23a                      5
sector 80                       5
sector 30                       5
new sector 2                    5
sector 36                       4
sector 12a                      4
new                             4
sector 3a                       4
sheetla colony                  3
sector 73                       3
sector 15                       3
sector 27                       3
sector 17b                      3
maruti kunj                     3
sector 88b                      3
sector 110 a                    3
patel nagar                     3
a block sector 43               3
b block sector 43               3
sector 17a                      3
sector-2 sohna road             3
surat nagar                     3
Name: count, dtype: int64

In [21]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [22]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [23]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
821,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
1458,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
2559,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2693,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [24]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [25]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1538,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,NaN,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2003,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2854,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3082,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3849,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [26]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [27]:
df.shape

(3829, 21)

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 81 Gurgaon,flat,signature global synera,sector 81,0.45,7525.0,598.0,Carpet area: 598 (55.56 sq.m.),2,2,2,store room,"011, Sector 81 Gurgaon, Gurgaon, Haryana",6.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...",Signature global is india's no.1 affordable ho...,"['3 Wardrobe', '3 Fan', '1 Exhaust Fan', '2 Ge...","['Power Back-up', 'Security / Fire Alarm', 'Li...","['Green Area4 out of 5', 'Construction3 out of..."
1,5 Bedroom House for sale in Sector 14 Gurgaon,house,independent,sector 14,4.15,18444.0,2250.0,Plot area 250(209.03 sq.m.),5,4,2,NaN,"Sector 14 Gurgaon, Gurgaon, Haryana",2.0,North-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",250 sqyds independent house for sale in sector...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2,3 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,sector 71,1.40,7945.0,1762.0,Carpet area: 1762 (163.7 sq.m.),3,3,2,pooja room,"Sector 71 Gurgaon, Gurgaon, Haryana",1.0,South-East,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Beautiful made with with 2 side view and ample...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction3 out of..."
3,9 Bedroom House for sale in Sector 47 Gurgaon,house,independent,sector 47,5.15,26615.0,1935.0,Plot area 215(179.77 sq.m.),9,9,3+,store room,"02120, Sector 47 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Corner 9bhk 215sq.Yd east facing independent f...,"['9 Wardrobe', '13 Fan', '1 Exhaust Fan', '23 ...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
4,2 BHK Flat in Sohna,flat,global height,sohna road,0.45,6338.0,710.0,Carpet area: 710 (65.96 sq.m.),2,2,2,not available,"Sohna, Gurgaon, Haryana",6.0,East,1 to 5 Year Old,NaN,Its totally ready to move properly and on highway,"['1 Water Purifier', '3 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [30]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [31]:
df.duplicated().sum()

np.int64(123)

In [33]:
df.to_csv('properties_1.csv',index=False)